INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('regla-metalica', 'Regla Metálica', 420, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', 'Herramientas', false, 'Regla metálica profesional para mediciones precisas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Regla metálica profesional para mediciones precisas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', related_categories = '{"Herramientas","Diseño de Cejas"}', name = 'Regla Metálica', price = 420, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('espejo-auxiliar-g', 'Espejo Auxiliar G', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/d_nq_np_638989-mlm42485527476_072020-w1-682f4c41249fc2a6f016034916189282-1024-1024.webp', 'Herramientas', false, 'Espejo auxiliar tamaño G para verificación de trabajo.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Espejo auxiliar tamaño G para verificación de trabajo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/d_nq_np_638989-mlm42485527476_072020-w1-682f4c41249fc2a6f016034916189282-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Espejo Auxiliar G', price = 200, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-pestanas-tira', 'Pinza para Pestañas de Tira', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza especializada para colocación de pestañas en tira.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza especializada para colocación de pestañas en tira.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Pestañas en Tira"}', name = 'Pinza para Pestañas de Tira', price = 100, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-depilar', 'Pinza para Depilar', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza profesional para depilación de cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional para depilación de cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Diseño de Cejas"}', name = 'Pinza para Depilar', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-punta-larga', 'Pinza Punta Larga', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza con punta larga para extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza con punta larga para extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Punta Larga', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-abanicos-sin-punta', 'Pinza Abanicos sin Punta', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza para crear abanicos sin punta. Ideal para técnica de volumen.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza para crear abanicos sin punta. Ideal para técnica de volumen.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Abanicos sin Punta', price = 100, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-punta-m12', 'Pinza Punta M-12', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza punta M-12 para extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza punta M-12 para extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Punta M-12', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-colocar-m18', 'Pinza para Colocar M-18', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza para colocar extensiones M-18.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza para colocar extensiones M-18.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza para Colocar M-18', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-ele-m19', 'Pinza Ele M-19', 140, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza Ele M-19 para técnica de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza Ele M-19 para técnica de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Ele M-19', price = 140, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-md14-punta', 'Pinza MD 14 en Punta', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza MD 14 con punta precisa para extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza MD 14 con punta precisa para extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza MD 14 en Punta', price = 200, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-md14-ele', 'Pinza MD 14 en Ele', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pinza MD 14 en forma de Ele.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza MD 14 en forma de Ele.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza MD 14 en Ele', price = 200, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('set-6-pinzas-tijera', 'Set 6 Pinzas y Tijera', 650, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Set completo de 6 pinzas profesionales y tijera para extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set completo de 6 pinzas profesionales y tijera para extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Set 6 Pinzas y Tijera', price = 650, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('set-5-pinceles', 'Set 5 Pinceles', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Set de 5 pinceles profesionales para diseño de cejas y aplicación.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de 5 pinceles profesionales para diseño de cejas y aplicación.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Diseño de Cejas"}', name = 'Set 5 Pinceles', price = 350, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('regla-curva-plastica', 'Regla Curva Plástica para Diseño', 65, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/arco-hilo_000131-98d2fedde55c00a63616035616219256-1024-1024.webp', 'Herramientas', false, 'Regla curva plástica para diseño preciso de cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Regla curva plástica para diseño preciso de cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/arco-hilo_000131-98d2fedde55c00a63616035616219256-1024-1024.webp', related_categories = '{"Herramientas","Diseño de Cejas"}', name = 'Regla Curva Plástica para Diseño', price = 65, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('peine-separador', 'Peine Separador de Pestañas', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Peine separador profesional para pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Peine separador profesional para pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Peine Separador de Pestañas', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('funda-pinza', 'Funda para Pinza', 30, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Funda protectora para pinzas de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Funda protectora para pinzas de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Funda para Pinza', price = 30, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('microbrush-100pz', 'Microbrush de 100 pz', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pack de 100 microbrush para aplicaciones de precisión.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 100 microbrush para aplicaciones de precisión.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Microbrush de 100 pz', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('100-microbrush-largo', '100 Microbrush Largo', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pack de 100 microbrush largos para procedimientos profesionales.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 100 microbrush largos para procedimientos profesionales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = '100 Microbrush Largo', price = 90, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('repuesto-maniqui-microblading', 'Repuesto de Maniquí para Microblading', 185, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/h64fbe6378cc249cd88ae27bcf74d9993y1-108b75012dae3f992515856923521717-1024-1024.webp', 'Herramientas', false, 'Repuesto de piel para maniquí de práctica de microblading.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Microblading"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Repuesto de piel para maniquí de práctica de microblading.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/h64fbe6378cc249cd88ae27bcf74d9993y1-108b75012dae3f992515856923521717-1024-1024.webp', related_categories = '{"Herramientas","Microblading"}', name = 'Repuesto de Maniquí para Microblading', price = 185, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('medidor-humedad', 'Medidor de Humedad', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', 'Herramientas', false, 'Medidor de humedad ambiental para control de condiciones óptimas en procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Medidor de humedad ambiental para control de condiciones óptimas en procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Medidor de Humedad', price = 250, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('gel-fijador-cejas', 'Gel Fijador para Diseño de Cejas', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-1024-1024.webp', 'Diseño de Cejas', false, 'Gel fijador profesional para diseño de cejas. Mantiene la forma del diseño.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Gel fijador profesional para diseño de cejas. Mantiene la forma del diseño.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-1024-1024.webp', related_categories = '{"Diseño de Cejas"}', name = 'Gel Fijador para Diseño de Cejas', price = 50, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('gel-reestructurante-cejas', 'Gel Reestructurante para Diseño de Cejas', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-1024-1024.webp', 'Diseño de Cejas', false, 'Gel reestructurante para diseño de cejas. Nutre y da forma.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Gel reestructurante para diseño de cejas. Nutre y da forma.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-1024-1024.webp', related_categories = '{"Diseño de Cejas"}', name = 'Gel Reestructurante para Diseño de Cejas', price = 60, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('stencil-cejas', 'Stencil para Cejas', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/36-plantilla-ceja-6-011-b4bfd48aa95fec631d15856942870032-1024-1024.webp', 'Diseño de Cejas', false, 'Stencil profesional para diseño rápido y simétrico de cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Stencil profesional para diseño rápido y simétrico de cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/36-plantilla-ceja-6-011-b4bfd48aa95fec631d15856942870032-1024-1024.webp', related_categories = '{"Diseño de Cejas"}', name = 'Stencil para Cejas', price = 50, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('delineador-pencil', 'Delineador Pencil', 40, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mesa-de-trabajo-21-5623fc474fe25629fd16687989657552-1024-1024.webp', 'Diseño de Cejas', false, 'Delineador tipo pencil disponible en 4 tonos para diseño de cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Delineador tipo pencil disponible en 4 tonos para diseño de cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mesa-de-trabajo-21-5623fc474fe25629fd16687989657552-1024-1024.webp', related_categories = '{"Diseño de Cejas"}', name = 'Delineador Pencil', price = 40, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('limpiador-piel-normal-seca', 'Limpiador de Impurezas Piel Normal y Seca', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/limpiador-de-impurezas-piel-mixta-y-piel-grasa-0e0ffdaf9bc06584a917561449421922-1024-1024.webp', 'Higiene', false, 'Limpiador de impurezas para piel normal y seca. Prepara la piel sin resecar.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Limpiador de impurezas para piel normal y seca. Prepara la piel sin resecar.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/limpiador-de-impurezas-piel-mixta-y-piel-grasa-0e0ffdaf9bc06584a917561449421922-1024-1024.webp', related_categories = '{"Higiene"}', name = 'Limpiador de Impurezas Piel Normal y Seca', price = 90, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;