INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-d-colores', 'Pestaña (D) en Colores', 600, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pes-d-015-11-53f06c333b890ae6c416577544212430-1024-1024.webp', 'Extensiones', false, 'Extensiones curva D en colores variados para looks creativos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva D en colores variados para looks creativos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pes-d-015-11-53f06c333b890ae6c416577544212430-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Pestaña (D) en Colores', price = 600, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-grupo-racimo', 'Pestañas en Grupo o Racimo', 32, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', 'Extensiones', false, 'Pestañas en grupo o racimo para aplicación rápida y efecto natural.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas en grupo o racimo para aplicación rápida y efecto natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Pestañas en Grupo o Racimo', price = 32, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-grupo-racimo-azul', 'Pestañas en Grupo o Racimo Azul', 22, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', 'Extensiones', false, 'Pestañas en grupo color azul para looks creativos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas en grupo color azul para looks creativos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Pestañas en Grupo o Racimo Azul', price = 22, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-grupo-racimo-cafe', 'Pestañas en Grupo o Racimo Café', 22, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', 'Extensiones', false, 'Pestañas en grupo color café para un look natural.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas en grupo color café para un look natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Pestañas en Grupo o Racimo Café', price = 22, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('modelos-de-curvas', 'Modelos de Curvas', 880, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', 'Extensiones', false, 'Set de modelos de curvas para demostración y práctica profesional.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de modelos de curvas para demostración y práctica profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Modelos de Curvas', price = 880, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-practica', 'Pestaña para Práctica', 55, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', 'Extensiones', false, 'Pestañas especiales para práctica de técnicas de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas especiales para práctica de técnicas de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/6d4ac5ec-8f5a-4c08-8907-05c497a5cbaf1-d7cd8a22073d7feac315894821721364-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Pestaña para Práctica', price = 55, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-individual-negra', 'Pestaña Individual (Negra)', 25, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-21_mesa-de-trabajo-11-285849cb951c114fde15856909430891-1024-1024.webp', 'Extensiones', false, 'Pestañas individuales color negro para aplicación pelo a pelo.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas individuales color negro para aplicación pelo a pelo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-21_mesa-de-trabajo-11-285849cb951c114fde15856909430891-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Pestaña Individual (Negra)', price = 25, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-americana-tira', 'Pestaña Americana de Tira', 20, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-1024-1024.webp', 'Pestañas en Tira', false, 'Pestaña americana de tira. Disponible en múltiples modelos (001, 005, 012, 015, 020, 038, 042, 046, 503, 505, 507, 600, 606, 747M, 747S, 747XS, 107).', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestaña americana de tira. Disponible en múltiples modelos (001, 005, 012, 015, 020, 038, 042, 046, 503, 505, 507, 600, 606, 747M, 747S, 747XS, 107).', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-1024-1024.webp', related_categories = '{"Pestañas en Tira"}', name = 'Pestaña Americana de Tira', price = 20, category = 'Pestañas en Tira', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-europea-tira', 'Pestaña Europea de Tira', 25, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-1024-1024.webp', 'Pestañas en Tira', false, 'Pestaña europea de tira J.Eyelash. Modelos 22-78 disponibles. Fibra suave de alta calidad.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestaña europea de tira J.Eyelash. Modelos 22-78 disponibles. Fibra suave de alta calidad.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-1024-1024.webp', related_categories = '{"Pestañas en Tira"}', name = 'Pestaña Europea de Tira', price = 25, category = 'Pestañas en Tira', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-decorada-tira', 'Pestaña Decorada de Tira', 20, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-1024-1024.webp', 'Pestañas en Tira', false, 'Pestañas decoradas para looks artísticos y eventos especiales. Múltiples modelos disponibles.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas decoradas para looks artísticos y eventos especiales. Múltiples modelos disponibles.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-1024-1024.webp', related_categories = '{"Pestañas en Tira"}', name = 'Pestaña Decorada de Tira', price = 20, category = 'Pestañas en Tira', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-balsamo-20gr', 'Adhesivo Bálsamo 20 gr', 260, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vol_mesa-de-trabajo-11-d61661ecf8820a785a16669241686028-1024-1024.webp', 'Adhesivos', false, 'Adhesivo bálsamo de 20 gramos. Fórmula suave ideal para pieles sensibles.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo bálsamo de 20 gramos. Fórmula suave ideal para pieles sensibles.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vol_mesa-de-trabajo-11-d61661ecf8820a785a16669241686028-1024-1024.webp', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Bálsamo 20 gr', price = 260, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-balsamo-butter-30gr', 'Adhesivo Bálsamo Butter 30 gr', 380, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vol_mesa-de-trabajo-11-d61661ecf8820a785a16669241686028-1024-1024.webp', 'Adhesivos', false, 'Adhesivo bálsamo Butter 30 gramos. Textura cremosa para mejor control.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo bálsamo Butter 30 gramos. Textura cremosa para mejor control.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vol_mesa-de-trabajo-11-d61661ecf8820a785a16669241686028-1024-1024.webp', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Bálsamo Butter 30 gr', price = 380, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tintura-topica-negro', 'Tintura Tópica - Negro', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pig-071-10ea3ab254a18fa68516691314001398-1024-1024.webp', 'Pigmentos', false, 'Tintura tópica profesional tono negro para cejas y pestañas. Color intenso y duradero.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pigmentos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tintura tópica profesional tono negro para cejas y pestañas. Color intenso y duradero.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pig-071-10ea3ab254a18fa68516691314001398-1024-1024.webp', related_categories = '{"Pigmentos"}', name = 'Tintura Tópica - Negro', price = 350, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('sellador-tintura-topica', 'Sellador para Tintura Tópica', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pig-071-10ea3ab254a18fa68516691314001398-1024-1024.webp', 'Pigmentos', false, 'Sellador complementario para tintura tópica. Fija el color y prolonga duración.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pigmentos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Sellador complementario para tintura tópica. Fija el color y prolonga duración.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pig-071-10ea3ab254a18fa68516691314001398-1024-1024.webp', related_categories = '{"Pigmentos"}', name = 'Sellador para Tintura Tópica', price = 350, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('activador-tintura-topica', 'Activador para Tintura Tópica', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/activador-henna-2-2398d7caec1193296817558879257390-1024-1024.webp', 'Pigmentos', false, 'Activador para tintura tópica. Necesario para la reacción de tinción.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pigmentos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Activador para tintura tópica. Necesario para la reacción de tinción.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/activador-henna-2-2398d7caec1193296817558879257390-1024-1024.webp', related_categories = '{"Pigmentos"}', name = 'Activador para Tintura Tópica', price = 350, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('reestructurante-pigmento', 'Reestructurante Pigmento para Cejas y Pestañas', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-1024-1024.webp', 'Pigmentos', false, 'Reestructurante para uso con pigmentos en cejas y pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pigmentos","Tratamientos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Reestructurante para uso con pigmentos en cejas y pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-1024-1024.webp', related_categories = '{"Pigmentos","Tratamientos"}', name = 'Reestructurante Pigmento para Cejas y Pestañas', price = 60, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('henna-directa-2', 'Henna Directa', 370, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', 'Brow Henna', false, 'Henna directa disponible en Castaño Medio y Castaño Obscuro.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Brow Henna"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Henna directa disponible en Castaño Medio y Castaño Obscuro.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', related_categories = '{"Brow Henna"}', name = 'Henna Directa', price = 370, category = 'Brow Henna', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('mezclador-henna', 'Mezclador de Henna', 180, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', 'Brow Henna', false, 'Mezclador profesional para preparación de henna.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Brow Henna","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Mezclador profesional para preparación de henna.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', related_categories = '{"Brow Henna","Herramientas"}', name = 'Mezclador de Henna', price = 180, category = 'Brow Henna', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('plantillas-cejas', 'Plantillas para Cejas', 120, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/36-plantilla-ceja-6-011-b4bfd48aa95fec631d15856942870032-1024-1024.webp', 'Diseño de Cejas', false, 'Set de plantillas para diseño de cejas. Múltiples modelos disponibles.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas","Brow Henna"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de plantillas para diseño de cejas. Múltiples modelos disponibles.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/36-plantilla-ceja-6-011-b4bfd48aa95fec631d15856942870032-1024-1024.webp', related_categories = '{"Diseño de Cejas","Brow Henna"}', name = 'Plantillas para Cejas', price = 120, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillos-pestanas-50', 'Cepillos para Pestañas con 50 pzas', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pack de 50 cepillos desechables para pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 50 cepillos desechables para pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Cepillos para Pestañas con 50 pzas', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillo-largo-100', 'Cepillo Largo para Pestañas 100 piezas', 260, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pack de 100 cepillos largos para pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 100 cepillos largos para pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Cepillo Largo para Pestañas 100 piezas', price = 260, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillo-con-guarda', 'Cepillo con Guarda', 85, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Cepillo para pestañas con guarda protectora.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cepillo para pestañas con guarda protectora.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = 'Cepillo con Guarda', price = 85, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('50-cepillos-pestanas', '50 Cepillos para Pestañas', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Herramientas', false, 'Pack de 50 cepillos para pestañas uso profesional.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 50 cepillos para pestañas uso profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Herramientas"}', name = '50 Cepillos para Pestañas', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('contenedor-mini-base', 'Contenedor Mini para Base', 15, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/base-031-a0f3cbfe23723e3c4f16691451059225-1024-1024.webp', 'Herramientas', false, 'Contenedor mini para depositar base de adhesivo.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Contenedor mini para depositar base de adhesivo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/base-031-a0f3cbfe23723e3c4f16691451059225-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Contenedor Mini para Base', price = 15, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('contenedor-anillo-50', 'Contenedor para Anillo con 50 pzas', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/base-031-a0f3cbfe23723e3c4f16691451059225-1024-1024.webp', 'Herramientas', false, 'Pack de 50 contenedores para anillo de adhesivo.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 50 contenedores para anillo de adhesivo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/base-031-a0f3cbfe23723e3c4f16691451059225-1024-1024.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Contenedor para Anillo con 50 pzas', price = 50, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;