INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-mink-curva-c', 'Pestañas Mink Curva C', 280, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', 'Extensiones', false, 'Pestañas de visón sintético de alta calidad. Curva C con acabado natural y elegante. Disponible en grosores 0.07, 0.10, 0.12, 0.15mm.', '{}', '{}', NULL, '{"Curva: C","Grosores: 0.07, 0.10, 0.12, 0.15mm","Material: Mink sintético premium","Acabado natural"}', '{}', NULL, '{"Extensiones","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas de visón sintético de alta calidad. Curva C con acabado natural y elegante. Disponible en grosores 0.07, 0.10, 0.12, 0.15mm.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', specifications = '{"Curva: C","Grosores: 0.07, 0.10, 0.12, 0.15mm","Material: Mink sintético premium","Acabado natural"}', related_categories = '{"Extensiones","Adhesivos"}', name = 'Pestañas Mink Curva C', price = 280, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-mink-curva-d', 'Pestañas Mink Curva D', 280, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pes-d-015-11-53f06c333b890ae6c416577544212430-1024-1024.webp', 'Extensiones', false, 'Pestañas de visón sintético de alta calidad. Curva D dramática para un efecto más abierto y llamativo.', '{}', '{}', NULL, '{"Curva: D (dramática)","Múltiples longitudes disponibles","Material: Mink sintético premium","Efecto abierto y llamativo"}', '{}', NULL, '{"Extensiones","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas de visón sintético de alta calidad. Curva D dramática para un efecto más abierto y llamativo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pes-d-015-11-53f06c333b890ae6c416577544212430-1024-1024.webp', specifications = '{"Curva: D (dramática)","Múltiples longitudes disponibles","Material: Mink sintético premium","Efecto abierto y llamativo"}', related_categories = '{"Extensiones","Adhesivos"}', name = 'Pestañas Mink Curva D', price = 280, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-gold-volumen', 'Pestañas Volumen Gold', 360, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/gob05c-0111-5aff9bdf2451c13d3f15329792899738-1024-1024.webp', 'Extensiones', false, 'Línea Gold premium para técnicas de volumen ruso. Ultra livianas con la mejor calidad de fibra para una aplicación perfecta.', '{"Línea Gold premium","Ultra livianas para volumen ruso","Fibra de la más alta calidad","Aplicación perfecta"}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Línea Gold premium para técnicas de volumen ruso. Ultra livianas con la mejor calidad de fibra para una aplicación perfecta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/gob05c-0111-5aff9bdf2451c13d3f15329792899738-1024-1024.webp', benefits = '{"Línea Gold premium","Ultra livianas para volumen ruso","Fibra de la más alta calidad","Aplicación perfecta"}', related_categories = '{"Extensiones","Adhesivos"}', name = 'Pestañas Volumen Gold', price = 360, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('extensiones-grupo-pro', 'Extensiones en Grupo PRO', 360, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-21_mesa-de-trabajo-11-285849cb951c114fde15856909430891-1024-1024.webp', 'Extensiones', false, 'Extensiones de pestañas en grupo para aplicación profesional. Pre-formadas para una aplicación rápida y uniforme con efecto natural.', '{"Pre-formadas para aplicación rápida","Efecto natural y uniforme","Ideal para técnica clásica avanzada","Fibra de alta calidad"}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones de pestañas en grupo para aplicación profesional. Pre-formadas para una aplicación rápida y uniforme con efecto natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-21_mesa-de-trabajo-11-285849cb951c114fde15856909430891-1024-1024.webp', benefits = '{"Pre-formadas para aplicación rápida","Efecto natural y uniforme","Ideal para técnica clásica avanzada","Fibra de alta calidad"}', related_categories = '{"Extensiones","Adhesivos"}', name = 'Extensiones en Grupo PRO', price = 360, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('base-pestanas', 'Base para Pestañas', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/base-031-a0f3cbfe23723e3c4f16691451059225-1024-1024.webp', 'Extensiones', false, 'Base protectora para pestañas. Prepara las pestañas naturales antes de la aplicación de extensiones, mejorando la adherencia y protegiendo la fibra natural.', '{}', '{}', NULL, '{"Prepara la pestaña natural","Mejora la adherencia","Protege la fibra natural"}', '{}', NULL, '{"Extensiones","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Base protectora para pestañas. Prepara las pestañas naturales antes de la aplicación de extensiones, mejorando la adherencia y protegiendo la fibra natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/base-031-a0f3cbfe23723e3c4f16691451059225-1024-1024.webp', specifications = '{"Prepara la pestaña natural","Mejora la adherencia","Protege la fibra natural"}', related_categories = '{"Extensiones","Adhesivos"}', name = 'Base para Pestañas', price = 50, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-supreme-g4', 'Adhesivo Supreme G4', 450, 550, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-11-07-a-las-21-36-331-dbf626e4d91ead894e16678787549429-1024-1024.webp', 'Adhesivos', false, 'Adhesivo de alta viscosidad y secado rápido (1-2 seg). Ideal para técnica clásica y volumen. Duración de 6 a 8 semanas con cuidado adecuado.', '{"Secado rápido 1-2 segundos","Alta viscosidad para control perfecto","Duración 6-8 semanas","Hipoalergénico"}', '{}', NULL, '{"Secado: 1-2 segundos","Duración: 6-8 semanas","Para técnica clásica y volumen","Color: Negro"}', '{}', NULL, '{"Adhesivos","Extensiones"}', 550, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo de alta viscosidad y secado rápido (1-2 seg). Ideal para técnica clásica y volumen. Duración de 6 a 8 semanas con cuidado adecuado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-11-07-a-las-21-36-331-dbf626e4d91ead894e16678787549429-1024-1024.webp', benefits = '{"Secado rápido 1-2 segundos","Alta viscosidad para control perfecto","Duración 6-8 semanas","Hipoalergénico"}', specifications = '{"Secado: 1-2 segundos","Duración: 6-8 semanas","Para técnica clásica y volumen","Color: Negro"}', related_categories = '{"Adhesivos","Extensiones"}', original_price = 550, name = 'Adhesivo Supreme G4', price = 450, category = 'Adhesivos', compare_at_price = 550, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-volumen', 'Adhesivo Volumen', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vol_mesa-de-trabajo-11-d61661ecf8820a785a16669241686028-1024-1024.webp', 'Adhesivos', false, 'Adhesivo Supreme para técnica de Volumen. Secado instantáneo, color negro intenso. Ideal para volumen 1 a 1, técnica japonesa, volumen ruso y pestañas dimensionales.', '{"Tiempo de secado instantáneo","Color negro intenso profesional","Alta resistencia al agua y humedad","Larga duración","Hipoalergénico para ojos sensibles","Textura de consistencia media"}', '{"Presentación de 8 ml"}', NULL, '{"Ingrediente principal: Ethyl-2-Cyanocrylate (grado médico)","Alcoxi-2-cianoacrilato para flexibilidad","PMMA para control de fijación","Negro de carbón 100% seguro"}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo Supreme para técnica de Volumen. Secado instantáneo, color negro intenso. Ideal para volumen 1 a 1, técnica japonesa, volumen ruso y pestañas dimensionales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vol_mesa-de-trabajo-11-d61661ecf8820a785a16669241686028-1024-1024.webp', benefits = '{"Tiempo de secado instantáneo","Color negro intenso profesional","Alta resistencia al agua y humedad","Larga duración","Hipoalergénico para ojos sensibles","Textura de consistencia media"}', includes = '{"Presentación de 8 ml"}', specifications = '{"Ingrediente principal: Ethyl-2-Cyanocrylate (grado médico)","Alcoxi-2-cianoacrilato para flexibilidad","PMMA para control de fijación","Negro de carbón 100% seguro"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Volumen', price = 250, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('after-care', 'After Care', 600, 700, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', 'Tratamientos', false, 'Tratamiento post-procedimiento para el cuidado y recuperación de pestañas y cejas. Hidrata, fortalece y protege la fibra natural después de cualquier procedimiento.', '{"Hidrata profundamente","Fortalece las pestañas naturales","Protege después del procedimiento","Uso diario recomendado"}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos","Lash Lifting"}', 700, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tratamiento post-procedimiento para el cuidado y recuperación de pestañas y cejas. Hidrata, fortalece y protege la fibra natural después de cualquier procedimiento.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', benefits = '{"Hidrata profundamente","Fortalece las pestañas naturales","Protege después del procedimiento","Uso diario recomendado"}', related_categories = '{"Tratamientos","Lash Lifting"}', original_price = 700, name = 'After Care', price = 600, category = 'Tratamientos', compare_at_price = 700, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('mascara-acondicionadora', 'Máscara Acondicionadora de Pestañas', 120, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mascara-con-queratina-y-vitamina-e-4-e0ac482677b85eddc017695390879846-1024-1024.webp', 'Tratamientos', false, 'Máscara acondicionadora que fortalece, nutre y alarga las pestañas naturales. Uso diario recomendado para resultados óptimos.', '{"Fortalece las pestañas","Nutre desde la raíz","Efecto alargador","Uso diario"}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Máscara acondicionadora que fortalece, nutre y alarga las pestañas naturales. Uso diario recomendado para resultados óptimos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mascara-con-queratina-y-vitamina-e-4-e0ac482677b85eddc017695390879846-1024-1024.webp', benefits = '{"Fortalece las pestañas","Nutre desde la raíz","Efecto alargador","Uso diario"}', related_categories = '{"Tratamientos"}', name = 'Máscara Acondicionadora de Pestañas', price = 120, category = 'Tratamientos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tratamiento-alargador', 'Tratamiento Alargador para Cejas y Pestañas', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', 'Tratamientos', true, 'Reestructura, fortalece y alarga las pestañas y cejas en tan solo 4 semanas de uso continuo. Fórmula vitaminada para resultados visibles.', '{"Resultados visibles en 4 semanas","Reestructura la fibra capilar","Fortalece pestañas y cejas","Fórmula vitaminada"}', '{}', 'Resultados visibles en 4 semanas', '{}', '{}', NULL, '{"Tratamientos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Reestructura, fortalece y alarga las pestañas y cejas en tan solo 4 semanas de uso continuo. Fórmula vitaminada para resultados visibles.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', benefits = '{"Resultados visibles en 4 semanas","Reestructura la fibra capilar","Fortalece pestañas y cejas","Fórmula vitaminada"}', performance = 'Resultados visibles en 4 semanas', related_categories = '{"Tratamientos"}', name = 'Tratamiento Alargador para Cejas y Pestañas', price = 150, category = 'Tratamientos', is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('perfilador-doble', 'Perfilador Doble - Paquete de 3 Pzs', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mesa-de-trabajo-21-5623fc474fe25629fd16687989657552-1024-1024.webp', 'Herramientas', false, 'Perfilador doble de precisión. Paquete de 3 piezas para diseño y definición profesional de cejas. Doble punta para versatilidad.', '{}', '{}', NULL, '{"Paquete de 3 piezas","Doble punta","Para diseño profesional"}', '{}', NULL, '{"Herramientas","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Perfilador doble de precisión. Paquete de 3 piezas para diseño y definición profesional de cejas. Doble punta para versatilidad.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mesa-de-trabajo-21-5623fc474fe25629fd16687989657552-1024-1024.webp', specifications = '{"Paquete de 3 piezas","Doble punta","Para diseño profesional"}', related_categories = '{"Herramientas","Diseño de Cejas"}', name = 'Perfilador Doble - Paquete de 3 Pzs', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('godete-cristal', 'Godete de Cristal', 295, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/81-cristal-redondo-grande-011-9e045060396cb69b3115856904456678-1024-1024.webp', 'Herramientas', false, 'Godete de cristal profesional para mezclas de pigmentos, tintes y adhesivos. Superficie lisa y fácil de limpiar. Ideal para trabajar con precisión.', '{}', '{}', NULL, '{"Cristal transparente de alta calidad","Superficie ultra lisa","Fácil limpieza y desinfección","Para mezclas de pigmentos y tintes"}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Godete de cristal profesional para mezclas de pigmentos, tintes y adhesivos. Superficie lisa y fácil de limpiar. Ideal para trabajar con precisión.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/81-cristal-redondo-grande-011-9e045060396cb69b3115856904456678-1024-1024.webp', specifications = '{"Cristal transparente de alta calidad","Superficie ultra lisa","Fácil limpieza y desinfección","Para mezclas de pigmentos y tintes"}', related_categories = '{"Herramientas"}', name = 'Godete de Cristal', price = 295, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('piedra-jade', 'Piedra de Jade', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/piedra-jade-011-d010fed6068f57234f15494015022538-1024-1024.webp', 'Herramientas', false, 'Piedra de jade natural para depositar adhesivo durante la aplicación de extensiones de pestañas. Mantiene la temperatura del adhesivo estable.', '{}', '{}', NULL, '{"Jade natural","Mantiene temperatura estable del adhesivo","Superficie fría y lisa","Tamaño ergonómico"}', '{}', NULL, '{"Herramientas","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Piedra de jade natural para depositar adhesivo durante la aplicación de extensiones de pestañas. Mantiene la temperatura del adhesivo estable.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/piedra-jade-011-d010fed6068f57234f15494015022538-1024-1024.webp', specifications = '{"Jade natural","Mantiene temperatura estable del adhesivo","Superficie fría y lisa","Tamaño ergonómico"}', related_categories = '{"Herramientas","Adhesivos"}', name = 'Piedra de Jade', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('maniqui-microblading', 'Maniquí Microblading', 300, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/h64fbe6378cc249cd88ae27bcf74d9993y1-108b75012dae3f992515856923521717-1024-1024.webp', 'Herramientas', false, 'Maniquí de práctica para perfeccionar la técnica de microblading. Piel realista para entrenar trazos y técnica antes de trabajar con clientes.', '{"Piel realista para práctica","Ideal para perfeccionar técnica","Reutilizable","Para principiantes y avanzados"}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Microblading"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Maniquí de práctica para perfeccionar la técnica de microblading. Piel realista para entrenar trazos y técnica antes de trabajar con clientes.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/h64fbe6378cc249cd88ae27bcf74d9993y1-108b75012dae3f992515856923521717-1024-1024.webp', benefits = '{"Piel realista para práctica","Ideal para perfeccionar técnica","Reutilizable","Para principiantes y avanzados"}', related_categories = '{"Herramientas","Microblading"}', name = 'Maniquí Microblading', price = 300, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('papel-termico', 'Papel Térmico', 35, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/papel-termico-1-cf28baf56f9440056117582324679872-1024-1024.webp', 'Herramientas', false, 'Papel térmico para citas y recibos. Rollo compatible con impresoras térmicas estándar.', '{}', '{}', NULL, '{"Compatible con impresoras térmicas","Rollo estándar"}', '{}', NULL, '{"Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Papel térmico para citas y recibos. Rollo compatible con impresoras térmicas estándar.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/papel-termico-1-cf28baf56f9440056117582324679872-1024-1024.webp', specifications = '{"Compatible con impresoras térmicas","Rollo estándar"}', related_categories = '{"Herramientas"}', name = 'Papel Térmico', price = 35, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lampara-media-luna', 'Lámpara Media Luna LED', 2600, 3000, 'https://acdn-us.mitiendanube.com/stores/694/809/products/led-02-011-81a2bfd1118ab4719116813240087351-1024-1024.webp', 'Accesorios', false, 'Lámpara profesional LED de media luna con luz ajustable. Ideal para trabajo de precisión en extensiones de pestañas y procedimientos estéticos.', '{"Luz LED ajustable en intensidad","Diseño ergonómico media luna","Iluminación sin sombras","Para trabajo de precisión"}', '{}', NULL, '{"Tipo: LED","Forma: Media Luna","Intensidad ajustable","Bajo consumo energético"}', '{}', NULL, '{"Accesorios"}', 3000, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Lámpara profesional LED de media luna con luz ajustable. Ideal para trabajo de precisión en extensiones de pestañas y procedimientos estéticos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/led-02-011-81a2bfd1118ab4719116813240087351-1024-1024.webp', benefits = '{"Luz LED ajustable en intensidad","Diseño ergonómico media luna","Iluminación sin sombras","Para trabajo de precisión"}', specifications = '{"Tipo: LED","Forma: Media Luna","Intensidad ajustable","Bajo consumo energético"}', related_categories = '{"Accesorios"}', original_price = 3000, name = 'Lámpara Media Luna LED', price = 2600, category = 'Accesorios', compare_at_price = 3000, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('compass-silver-ratio', 'Compass Silver Ratio', 1270, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', 'Accesorios', false, 'Compás de proporción áurea para mediciones precisas en micropigmentación y diseño de cejas. Herramienta premium de acero inoxidable.', '{}', '{}', NULL, '{"Material: Acero inoxidable","Proporción áurea integrada","Para micropigmentación y diseño","Calidad premium"}', '{}', NULL, '{"Accesorios","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Compás de proporción áurea para mediciones precisas en micropigmentación y diseño de cejas. Herramienta premium de acero inoxidable.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', specifications = '{"Material: Acero inoxidable","Proporción áurea integrada","Para micropigmentación y diseño","Calidad premium"}', related_categories = '{"Accesorios","Diseño de Cejas"}', name = 'Compass Silver Ratio', price = 1270, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lash-shampoo', 'Lash Shampoo Espuma', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/lash-shampoo-toronja-3-7e48d947857ba7bde617702337947545-1024-1024.webp', 'Higiene', false, 'Limpieza profunda de párpados y pestañas. Esencial para la asepsia y retención de extensiones. Espuma suave que no irrita.', '{"Limpieza profunda sin irritar","Mejora la retención de extensiones","Espuma suave","Para uso diario"}', '{}', NULL, '{}', '{}', NULL, '{"Higiene","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Limpieza profunda de párpados y pestañas. Esencial para la asepsia y retención de extensiones. Espuma suave que no irrita.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/lash-shampoo-toronja-3-7e48d947857ba7bde617702337947545-1024-1024.webp', benefits = '{"Limpieza profunda sin irritar","Mejora la retención de extensiones","Espuma suave","Para uso diario"}', related_categories = '{"Higiene","Extensiones"}', name = 'Lash Shampoo Espuma', price = 100, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('agua-micelar', 'Agua Micelar J.Denis', 75, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/agua_mesa-de-trabajo-1-29698059ab235edcb517344065964817-1024-1024.webp', 'Higiene', false, 'Remoción suave de maquillaje sin comprometer la barrera cutánea. Apto para pieles sensibles. Fórmula suave y efectiva.', '{"Remoción suave de maquillaje","No compromete la barrera cutánea","Apto para pieles sensibles","Sin alcohol"}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Remoción suave de maquillaje sin comprometer la barrera cutánea. Apto para pieles sensibles. Fórmula suave y efectiva.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/agua_mesa-de-trabajo-1-29698059ab235edcb517344065964817-1024-1024.webp', benefits = '{"Remoción suave de maquillaje","No compromete la barrera cutánea","Apto para pieles sensibles","Sin alcohol"}', related_categories = '{"Higiene"}', name = 'Agua Micelar J.Denis', price = 75, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tonificante-desinfectante', 'Tonificante Desinfectante', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/tmp_b64_f238b6e6-d105-422b-ad5a-6bc44dcc9d65_694809_702700-a4793955e071714ede17460410086368-1024-1024.webp', 'Higiene', false, 'Sanitizante de amplio espectro. Bactericida y viricida para piel y herramientas de trabajo. Esencial para la higiene profesional.', '{}', '{}', NULL, '{"Bactericida y viricida","Para piel y herramientas","Amplio espectro","Uso profesional"}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Sanitizante de amplio espectro. Bactericida y viricida para piel y herramientas de trabajo. Esencial para la higiene profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/tmp_b64_f238b6e6-d105-422b-ad5a-6bc44dcc9d65_694809_702700-a4793955e071714ede17460410086368-1024-1024.webp', specifications = '{"Bactericida y viricida","Para piel y herramientas","Amplio espectro","Uso profesional"}', related_categories = '{"Higiene"}', name = 'Tonificante Desinfectante', price = 90, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('limpiador-impurezas', 'Limpiador de Impurezas - Piel Mixta y Grasa', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/limpiador-de-impurezas-piel-mixta-y-piel-grasa-0e0ffdaf9bc06584a917561449421922-1024-1024.webp', 'Higiene', false, 'Limpiador especializado para pieles mixtas y grasas. Elimina impurezas y exceso de grasa preparando la piel para procedimientos de cejas y pestañas.', '{"Especial para piel mixta y grasa","Elimina impurezas profundamente","Prepara la piel para procedimientos","No reseca la piel"}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Limpiador especializado para pieles mixtas y grasas. Elimina impurezas y exceso de grasa preparando la piel para procedimientos de cejas y pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/limpiador-de-impurezas-piel-mixta-y-piel-grasa-0e0ffdaf9bc06584a917561449421922-1024-1024.webp', benefits = '{"Especial para piel mixta y grasa","Elimina impurezas profundamente","Prepara la piel para procedimientos","No reseca la piel"}', related_categories = '{"Higiene"}', name = 'Limpiador de Impurezas - Piel Mixta y Grasa', price = 90, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-curva-c', 'Pad Curva C', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad de silicón con curva C para lash lifting. Diseño que proporciona una curvatura dramática y definida.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón con curva C para lash lifting. Diseño que proporciona una curvatura dramática y definida.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Curva C', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-rosa-sin-canales', 'Pad Rosa sin Canales', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad rosa liso sin canales para lash lifting con acabado suave.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad rosa liso sin canales para lash lifting con acabado suave.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Rosa sin Canales', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-superior-inferior', 'Pad Superior e Inferior', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Set de pads para párpado superior e inferior. Cobertura completa para lifting profesional.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de pads para párpado superior e inferior. Cobertura completa para lifting profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Superior e Inferior', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-colors-8p', 'Pad Colors 8p', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Set de 8 pads de colores para lash lifting. Variedad de tamaños y curvaturas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de 8 pads de colores para lash lifting. Variedad de tamaños y curvaturas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Colors 8p', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;