INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('soporte-pestanas-silicon', 'Soporte de Pestañas de Silicón', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Soporte de silicón para organizar pestañas durante el procedimiento.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Soporte de silicón para organizar pestañas durante el procedimiento.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Soporte de Pestañas de Silicón', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('protector-parpado-20', 'Protector para Párpado 20 pares', 40, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Accesorios', false, 'Protectores de gel para párpado inferior. Paquete de 20 pares.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Protectores de gel para párpado inferior. Paquete de 20 pares.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Protector para Párpado 20 pares', price = 40, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('protector-parpado-70', 'Protector para Párpado 70 pares', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Accesorios', false, 'Protectores de gel para párpado inferior. Paquete de 70 pares.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Protectores de gel para párpado inferior. Paquete de 70 pares.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Protector para Párpado 70 pares', price = 70, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('espejo-pestanas', 'Espejo para Pestañas', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Espejo auxiliar para verificar la colocación de extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Espejo auxiliar para verificar la colocación de extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Espejo para Pestañas', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillo-individual-pestanas', 'Cepillo Individual para Pestañas', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Accesorios', false, 'Cepillo individual para peinar y separar extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cepillo individual para peinar y separar extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Cepillo Individual para Pestañas', price = 100, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('anillo-10-contenedores', 'Anillo con 10 Contenedores', 30, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Accesorios', false, 'Anillo con 10 contenedores para adhesivo y productos durante procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Anillo con 10 contenedores para adhesivo y productos durante procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Anillo con 10 Contenedores', price = 30, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('anillo-copa-volumen-10', 'Anillo Copa Volumen 10 pzas', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Accesorios', false, 'Anillo tipo copa para volumen. Paquete de 10 piezas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Anillo tipo copa para volumen. Paquete de 10 piezas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Anillo Copa Volumen 10 pzas', price = 50, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cinta-adhesiva-ext', 'Cinta Adhesiva', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-plastico11-a71209ec9ed985a90016034886124545-480-0.webp', 'Accesorios', false, 'Cinta adhesiva para protección durante procedimientos de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cinta adhesiva para protección durante procedimientos de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-plastico11-a71209ec9ed985a90016034886124545-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Cinta Adhesiva', price = 50, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cinta-microfoam', 'Cinta Microfoam', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-microfoam11-8f139166d09bc9572916034888094159-480-0.webp', 'Accesorios', false, 'Cinta microfoam profesional para protección de párpados durante extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cinta microfoam profesional para protección de párpados durante extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-microfoam11-8f139166d09bc9572916034888094159-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Cinta Microfoam', price = 100, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('espatula-cosmetica', 'Espátula Cosmética', 20, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/23_mesa-de-trabajo-11-259e00bae1071806dc16687974095793-480-0.webp', 'Accesorios', false, 'Espátula para mezclar pigmentos, cremas o retirar producto de manera higiénica.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Espátula para mezclar pigmentos, cremas o retirar producto de manera higiénica.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/23_mesa-de-trabajo-11-259e00bae1071806dc16687974095793-480-0.webp', related_categories = '{"Accesorios"}', name = 'Espátula Cosmética', price = 20, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('microbrush-10', 'Microbrush 10 pzas', 35, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', 'Accesorios', false, 'Microaplicadores desechables para aplicación precisa. Paquete de 10 piezas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Microaplicadores desechables para aplicación precisa. Paquete de 10 piezas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', related_categories = '{"Accesorios"}', name = 'Microbrush 10 pzas', price = 35, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillos10-pestanas', 'Cepillos para Pestañas 10 pzas', 40, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', 'Accesorios', false, 'Cepillos desechables para pestañas. Paquete de 10 piezas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cepillos desechables para pestañas. Paquete de 10 piezas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', related_categories = '{"Accesorios"}', name = 'Cepillos para Pestañas 10 pzas', price = 40, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillos-50-piezas', 'Cepillos para Pestañas 50 pzas', 65, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', 'Accesorios', false, 'Cepillos desechables para pestañas. Paquete de 50 piezas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cepillos desechables para pestañas. Paquete de 50 piezas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', related_categories = '{"Accesorios"}', name = 'Cepillos para Pestañas 50 pzas', price = 65, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cepillo-largo-100pz', 'Cepillo Largo para Pestañas 100 pzas', 260, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', 'Accesorios', false, 'Cepillos largos para pestañas. Paquete de 100 piezas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cepillos largos para pestañas. Paquete de 100 piezas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/micro10-031-bf736fe965e0d7493b16691440926657-480-0.webp', related_categories = '{"Accesorios"}', name = 'Cepillo Largo para Pestañas 100 pzas', price = 260, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lash-shampo-espuma', 'Lash Shampo Espuma', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-480-0.webp', 'Higiene', false, 'Shampoo en espuma para limpieza de extensiones de pestañas y pestañas naturales.', '{"Limpieza suave","No daña extensiones"}', '{}', NULL, '{}', '{}', NULL, '{"Higiene","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Shampoo en espuma para limpieza de extensiones de pestañas y pestañas naturales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-480-0.webp', benefits = '{"Limpieza suave","No daña extensiones"}', related_categories = '{"Higiene","Extensiones"}', name = 'Lash Shampo Espuma', price = 100, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('desmaquillante-bifasico', 'Desmaquillante Bifásico', 75, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-480-0.webp', 'Higiene', false, 'Desmaquillante bifásico suave para limpieza de ojos y extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Desmaquillante bifásico suave para limpieza de ojos y extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-480-0.webp', related_categories = '{"Higiene"}', name = 'Desmaquillante Bifásico', price = 75, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('desinfectante-pinzas-pads', 'Desinfectante para Pinzas y Pads', 75, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-480-0.webp', 'Higiene', false, 'Desinfectante profesional para limpieza de pinzas y pads de lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Desinfectante profesional para limpieza de pinzas y pads de lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-480-0.webp', related_categories = '{"Higiene","Herramientas"}', name = 'Desinfectante para Pinzas y Pads', price = 75, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('brocha-limpieza', 'Brocha para Limpieza', 120, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Higiene', false, 'Brocha profesional para limpieza de pestañas antes de procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Brocha profesional para limpieza de pestañas antes de procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Higiene","Extensiones"}', name = 'Brocha para Limpieza', price = 120, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cubrebocas', 'Cubrebocas', 25, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mica1-1ead16074c150b7c3f15494014566587-480-0.webp', 'Higiene', false, 'Cubrebocas desechable para protección durante procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cubrebocas desechable para protección durante procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mica1-1ead16074c150b7c3f15494014566587-480-0.webp', related_categories = '{"Higiene"}', name = 'Cubrebocas', price = 25, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('seis-caretas-faciales', 'Seis Caretas Faciales', 120, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mica1-1ead16074c150b7c3f15494014566587-480-0.webp', 'Higiene', false, 'Paquete de 6 caretas faciales protectoras para procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paquete de 6 caretas faciales protectoras para procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mica1-1ead16074c150b7c3f15494014566587-480-0.webp', related_categories = '{"Higiene"}', name = 'Seis Caretas Faciales', price = 120, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pano-limpiador-boquilla', 'Paño Limpiador de Boquilla', 120, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Accesorios', false, 'Paño profesional para limpieza de boquilla de pegamento.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paño profesional para limpieza de boquilla de pegamento.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Paño Limpiador de Boquilla', price = 120, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('vernier', 'Vernier', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Vernier de precisión para medir largo de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Vernier de precisión para medir largo de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Vernier', price = 60, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('j-eyebrow', 'J.EYEBROW', 25, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', 'Diseño de Cejas', false, 'Producto J.EYEBROW para diseño rápido de cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Producto J.EYEBROW para diseño rápido de cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', related_categories = '{"Diseño de Cejas"}', name = 'J.EYEBROW', price = 25, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('exhibidor-tiras', 'Exhibidor de Tiras', 300, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Exhibidor profesional para mostrar pestañas de tira en punto de venta.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Exhibidor profesional para mostrar pestañas de tira en punto de venta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Pestañas en Tira"}', name = 'Exhibidor de Tiras', price = 300, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('glue-shaker', 'Glue Shaker', 650, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/shaker_mesa-de-trabajo-1-copia-4e0418ae0983baf4f617344074504573-480-0.webp', 'Herramientas', false, 'Agitador eléctrico de adhesivo para extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Agitador eléctrico de adhesivo para extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/shaker_mesa-de-trabajo-1-copia-4e0418ae0983baf4f617344074504573-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Glue Shaker', price = 650, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;