INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-curva-c-015', 'Pestaña | Curva C | 0.15', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Extensiones', false, 'Pestaña individual Curva C grosor 0.15mm.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestaña individual Curva C grosor 0.15mm.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Extensiones"}', name = 'Pestaña | Curva C | 0.15', price = 350, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-curva-d-015', 'Pestaña | Curva D | 0.15', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Extensiones', false, 'Pestaña individual Curva D grosor 0.15mm.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestaña individual Curva D grosor 0.15mm.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Extensiones"}', name = 'Pestaña | Curva D | 0.15', price = 350, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-volumen-a1', 'Pinza Volumen Extensiones Mod. A1', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza profesional para extensiones de volumen modelo A1.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional para extensiones de volumen modelo A1.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Volumen Extensiones Mod. A1', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-volumen-a2', 'Pinza Volumen Extensiones Mod. A2', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza profesional para extensiones de volumen modelo A2.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional para extensiones de volumen modelo A2.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Volumen Extensiones Mod. A2', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-ele-extensiones', 'Pinza Ele para Extensiones', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza en forma de L para colocar extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza en forma de L para colocar extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Ele para Extensiones', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-punta-extensiones', 'Pinza Punta para Extensiones', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza de punta fina para aislar y colocar extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza de punta fina para aislar y colocar extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Punta para Extensiones', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-colocar', 'Pinza para Colocar', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza profesional para colocar extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional para colocar extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza para Colocar', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-volumen-tva4', 'Pinza Volumen Cod: TVA4', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza de volumen modelo TVA4 para extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza de volumen modelo TVA4 para extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Volumen Cod: TVA4', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-vetus-mcs18', 'Pinza Vetus MCS-18', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza profesional Vetus modelo MCS-18. Acero de alta calidad.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional Vetus modelo MCS-18. Acero de alta calidad.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Vetus MCS-18', price = 250, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-vetus-mcs12', 'Pinza Vetus MCS-12', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza profesional Vetus modelo MCS-12. Acero de alta calidad.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional Vetus modelo MCS-12. Acero de alta calidad.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Vetus MCS-12', price = 250, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-keratina-grupo', 'Pinza Extensiones en Grupo con Keratina', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Pinza para extensiones en grupo con recubrimiento de keratina.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza para extensiones en grupo con recubrimiento de keratina.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Extensiones en Grupo con Keratina', price = 70, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('botox-cejas-pestanas', 'Botox para Cejas y Pestañas', 600, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-480-0.webp', 'Tratamientos', true, 'Kit completo de Botox para cejas y pestañas. Nutre, engrosa y fortalece desde la raíz.', '{"Engrosamiento","Nutrición profunda","Fortalecimiento"}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit completo de Botox para cejas y pestañas. Nutre, engrosa y fortalece desde la raíz.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-480-0.webp', benefits = '{"Engrosamiento","Nutrición profunda","Fortalecimiento"}', related_categories = '{"Tratamientos","Lash Lifting"}', name = 'Botox para Cejas y Pestañas', price = 600, category = 'Tratamientos', is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cisteamina-lash-brows-kit', 'Cisteamina Lash & Brows', 1800, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-480-0.webp', 'Tratamientos', true, 'Kit profesional de Cisteamina para tratamiento de pestañas y cejas. Alternativa avanzada al lifting tradicional.', '{"Fórmula de cisteamina","Menos agresivo","Resultados superiores"}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit profesional de Cisteamina para tratamiento de pestañas y cejas. Alternativa avanzada al lifting tradicional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-480-0.webp', benefits = '{"Fórmula de cisteamina","Menos agresivo","Resultados superiores"}', related_categories = '{"Tratamientos","Lash Lifting"}', name = 'Cisteamina Lash & Brows', price = 1800, category = 'Tratamientos', is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('laminado-cisteamina', 'Laminado Cisteamina Estabilizada', 1500, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-480-0.webp', 'Tratamientos', false, 'Kit profesional de laminado con cisteamina estabilizada. Resultados premium para cejas.', '{"Cisteamina estabilizada","Resultados duraderos","Sin dañar la fibra capilar"}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit profesional de laminado con cisteamina estabilizada. Resultados premium para cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-480-0.webp', benefits = '{"Cisteamina estabilizada","Resultados duraderos","Sin dañar la fibra capilar"}', related_categories = '{"Tratamientos","Diseño de Cejas"}', name = 'Laminado Cisteamina Estabilizada', price = 1500, category = 'Tratamientos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pro-lash-lifting-kit', 'PRO Lash Lifting', 385, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Lash Lifting', false, 'Kit PRO Lash Lifting. Versión compacta profesional del kit de lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit PRO Lash Lifting. Versión compacta profesional del kit de lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'PRO Lash Lifting', price = 385, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('clips-lifting', 'Clips para Lifting', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Lash Lifting', false, 'Set de clips profesionales para procedimiento de lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de clips profesionales para procedimiento de lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Lash Lifting","Herramientas"}', name = 'Clips para Lifting', price = 350, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-aro', 'Pad Aro', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Lash Lifting', false, 'Pad en forma de aro para lifting. Diseño ergonómico.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad en forma de aro para lifting. Diseño ergonómico.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Aro', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('espatula-plastica-lifting', 'Espátula Plástica - Lifting', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Lash Lifting', false, 'Espátula plástica para aplicación de productos durante lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Espátula plástica para aplicación de productos durante lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Lash Lifting","Herramientas"}', name = 'Espátula Plástica - Lifting', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('crema-lash-lifting-ind', 'Crema Lash Lifting', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Lash Lifting', false, 'Crema individual para lash lifting. Repuesto para kit.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Crema individual para lash lifting. Repuesto para kit.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Crema Lash Lifting', price = 100, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('crema-fijadora-lifting-ind', 'Crema Fijadora Lifting', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Lash Lifting', false, 'Crema fijadora individual para lash lifting. Repuesto para kit.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Crema fijadora individual para lash lifting. Repuesto para kit.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Crema Fijadora Lifting', price = 100, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rollo-plastico-osmotico', 'Rollo Plástico Osmótico', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Lash Lifting', false, 'Rollo de plástico osmótico para potenciar el efecto del lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rollo de plástico osmótico para potenciar el efecto del lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Lash Lifting","Accesorios"}', name = 'Rollo Plástico Osmótico', price = 80, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('brow-fixative-soap', 'Brow Fixative - Brow Soap', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', 'Diseño de Cejas', false, 'Jabón fijador para cejas. Efecto brow lamination natural.', '{"Fijación duradera","Acabado natural"}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Jabón fijador para cejas. Efecto brow lamination natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', benefits = '{"Fijación duradera","Acabado natural"}', related_categories = '{"Diseño de Cejas"}', name = 'Brow Fixative - Brow Soap', price = 70, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cristal-adhesivo-65', 'Cristal para Adhesivo 6.5 cm', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Cristal de 6.5 cm para depositar adhesivo de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cristal de 6.5 cm para depositar adhesivo de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Cristal para Adhesivo 6.5 cm', price = 100, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cristal-adhesivo-45', 'Cristal para Adhesivo 4.5 cm', 80, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Cristal de 4.5 cm para depositar adhesivo de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cristal de 4.5 cm para depositar adhesivo de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Cristal para Adhesivo 4.5 cm', price = 80, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('holder-cristal', 'Holder Cristal', 140, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Soporte holder para cristal de adhesivo.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Soporte holder para cristal de adhesivo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Holder Cristal', price = 140, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;