INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-colors-6p', 'Pad Colors 6p', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Set de 6 pads de colores para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de 6 pads de colores para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Colors 6p', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-oso', 'Pad Oso', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad con forma de oso para lash lifting. Diseño único que facilita la separación de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad con forma de oso para lash lifting. Diseño único que facilita la separación de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Oso', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-corrector-reversion', 'Pad Corrector (Reversión)', 300, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad especial para corrección y reversión de lifting. Ideal para corregir curvaturas no deseadas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad especial para corrección y reversión de lifting. Ideal para corregir curvaturas no deseadas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Corrector (Reversión)', price = 300, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-2-en-1', 'Pad 2 en 1', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad versátil 2 en 1 para lash lifting con doble funcionalidad.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad versátil 2 en 1 para lash lifting con doble funcionalidad.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad 2 en 1', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-mariposa', 'Pad Mariposa', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad con forma de mariposa para un lifting con efecto abierto y natural.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad con forma de mariposa para un lifting con efecto abierto y natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Mariposa', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-elevacion-l', 'Pad Elevación L', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pad de elevación L para lifting con máxima curvatura y apertura.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de elevación L para lifting con máxima curvatura y apertura.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Elevación L', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-ld-simetricos', 'Pad LD Simétricos', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pads LD simétricos para lifting uniforme y equilibrado.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pads LD simétricos para lifting uniforme y equilibrado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Pad LD Simétricos', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pro-lash-lifting', 'PRO Lash Lifting', 385, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', 'Lash Lifting', false, 'Kit PRO de lash lifting con fórmula mejorada para resultados profesionales superiores.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit PRO de lash lifting con fórmula mejorada para resultados profesionales superiores.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'PRO Lash Lifting', price = 385, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-individual-pads', 'Adhesivo Individual para Pads - Lifting', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind_mesa-de-trabajo-11-dfc574ad69672ed3c216687966538196-1024-1024.webp', 'Lash Lifting', false, 'Adhesivo individual para pads de lifting. Fijación precisa y segura.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo individual para pads de lifting. Fijación precisa y segura.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind_mesa-de-trabajo-11-dfc574ad69672ed3c216687966538196-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Adhesivo Individual para Pads - Lifting', price = 60, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lifting-tool-espatula', 'Lifting Tool - Espátula Elevadora', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Lash Lifting', false, 'Espátula elevadora profesional para lifting de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Espátula elevadora profesional para lifting de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Lash Lifting","Herramientas"}', name = 'Lifting Tool - Espátula Elevadora', price = 100, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lash-tool-2en1', 'Lash Tool 2 en 1', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Lash Lifting', false, 'Herramienta 2 en 1 para lifting de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Herramienta 2 en 1 para lifting de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Lash Lifting","Herramientas"}', name = 'Lash Tool 2 en 1', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('reestructurante-lifting', 'Reestructurante Lifting', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-1024-1024.webp', 'Lash Lifting', false, 'Reestructurante para uso en procedimientos de lifting de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Tratamientos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Reestructurante para uso en procedimientos de lifting de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-1024-1024.webp', related_categories = '{"Lash Lifting","Tratamientos"}', name = 'Reestructurante Lifting', price = 60, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('locion-limpiadora-lifting', 'Loción Limpiadora Lifting', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-031-3e42554c91778a025516687967769318-1024-1024.webp', 'Lash Lifting', false, 'Loción limpiadora especializada para procedimientos de lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Loción limpiadora especializada para procedimientos de lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-031-3e42554c91778a025516687967769318-1024-1024.webp', related_categories = '{"Lash Lifting","Higiene"}', name = 'Loción Limpiadora Lifting', price = 60, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('locion-vitaminada', 'Loción Vitaminada', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', 'Lash Lifting', false, 'Loción vitaminada nutritiva para tratamiento post-lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Tratamientos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Loción vitaminada nutritiva para tratamiento post-lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', related_categories = '{"Lash Lifting","Tratamientos"}', name = 'Loción Vitaminada', price = 60, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('mini-cepillo-laminado', 'Mini Cepillo para Laminado', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Lash Lifting', false, 'Mini cepillo especializado para procedimientos de laminado.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Mini cepillo especializado para procedimientos de laminado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Mini Cepillo para Laminado', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('mini-cepillo-lash-lifting', 'Mini Cepillo para Lash Lifting', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Lash Lifting', false, 'Mini cepillo para aplicación precisa en lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Mini cepillo para aplicación precisa en lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Mini Cepillo para Lash Lifting', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('50-cepillo-mini-laminado', '50 Cepillo Mini para Laminado', 300, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Lash Lifting', false, 'Pack de 50 mini cepillos para laminado. Uso desechable y profesional.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pack de 50 mini cepillos para laminado. Uso desechable y profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = '50 Cepillo Mini para Laminado', price = 300, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cisteamina-lash-brows', 'Cisteamina Lash & Brows', 1800, 2100, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', 'Lash Lifting', false, 'Fórmula avanzada de cisteamina para lash lifting y laminado de cejas. Tecnología de última generación.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Diseño de Cejas"}', 2100, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Fórmula avanzada de cisteamina para lash lifting y laminado de cejas. Tecnología de última generación.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', related_categories = '{"Lash Lifting","Diseño de Cejas"}', original_price = 2100, name = 'Cisteamina Lash & Brows', price = 1800, category = 'Lash Lifting', compare_at_price = 2100, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('laminado-cisteamina-est', 'Laminado Cisteamina Estabilizada', 1500, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', 'Lash Lifting', false, 'Kit de laminado con cisteamina estabilizada. Resultados duraderos y seguros.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit de laminado con cisteamina estabilizada. Resultados duraderos y seguros.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', related_categories = '{"Lash Lifting"}', name = 'Laminado Cisteamina Estabilizada', price = 1500, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('shot-hidratante-15', '1.5 Shot Hidratante', 650, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', 'Tratamientos', false, 'Shot hidratante concentrado para nutrición intensiva de pestañas y cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Shot hidratante concentrado para nutrición intensiva de pestañas y cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', related_categories = '{"Tratamientos","Lash Lifting"}', name = '1.5 Shot Hidratante', price = 650, category = 'Tratamientos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-adhesivos-m-ch', 'Rulos Adhesivos Curva M/CH', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/53-rulos-adhesivos-031-2ade2563ab84da548d15314940318959-1024-1024.webp', 'Lash Curling', false, 'Rulos con adhesivo integrado curva M/CH para rizado de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Curling"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos con adhesivo integrado curva M/CH para rizado de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/53-rulos-adhesivos-031-2ade2563ab84da548d15314940318959-1024-1024.webp', related_categories = '{"Lash Curling"}', name = 'Rulos Adhesivos Curva M/CH', price = 70, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('curva-b-010-combo', 'Curva B | 0.10 | Mixta', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdb15co-011-0fef63a529a3684df815330546086769-1024-1024.webp', 'Extensiones', false, 'Extensiones curva B grosor 0.10 en presentación mixta.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva B grosor 0.10 en presentación mixta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdb15co-011-0fef63a529a3684df815330546086769-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Curva B | 0.10 | Mixta', price = 350, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('curva-c-010-combo', 'Curva C | 0.10 | Mixta', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-011-82b84a8a4aa5f3ec2615330546508985-1024-1024.webp', 'Extensiones', false, 'Extensiones curva C grosor 0.10 en presentación mixta.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva C grosor 0.10 en presentación mixta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-011-82b84a8a4aa5f3ec2615330546508985-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Curva C | 0.10 | Mixta', price = 350, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('curva-l-010-combo', 'Curva L | 0.10 | Mixta', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', 'Extensiones', false, 'Extensiones curva L grosor 0.10 en presentación mixta.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva L grosor 0.10 en presentación mixta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Curva L | 0.10 | Mixta', price = 350, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('curva-l-015-combo', 'Curva L | 0.15 | Mixta', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', 'Extensiones', false, 'Extensiones curva L grosor 0.15 en presentación mixta.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva L grosor 0.15 en presentación mixta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/jdc15co-0211-60d5279f4e8338fe8a15330550618599-1024-1024.webp', related_categories = '{"Extensiones"}', name = 'Curva L | 0.15 | Mixta', price = 350, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;