INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('kit-lash-lifting-profesional', 'Kit Lash Lifting Profesional J.Denis', 850, 950, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', 'Lash Lifting', true, 'Realza la belleza natural de tus pestañas. Eleva, alisa y engrosa tus pestañas desde la base, logrando un efecto de mayor longitud y curvatura de manera natural. Su fórmula hipoalergénica es segura y suave, proporcionando resultados duraderos.', '{"Pestañas visiblemente más largas sin extensiones","Curvatura natural y duradera","Seguro para todo tipo de pestañas gracias a su fórmula hipoalergénica","Fácil aplicación con resultados profesionales"}', '{"Crema Lash Lifting","Crema Fijadora","Loción Limpiadora","Loción Vitaminada","Pigmento para Pestañas","Reactor para pigmento","Gel Reestructurante","5 Lifting Pads (SS, S, M, L, LL)","Adhesivo para pads","Máscara en Gel Acondicionadora","20 Protectores de Párpados","10 Aplicadores con espátula","4 Microcepillos","4 Cepillos para Pestañas","2 Anillos","10 Contenedores"}', 'Hasta 35 aplicaciones', '{}', '{}', NULL, '{"Lash Lifting","Tratamientos"}', 950, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Realza la belleza natural de tus pestañas. Eleva, alisa y engrosa tus pestañas desde la base, logrando un efecto de mayor longitud y curvatura de manera natural. Su fórmula hipoalergénica es segura y suave, proporcionando resultados duraderos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-1024-1024.webp', benefits = '{"Pestañas visiblemente más largas sin extensiones","Curvatura natural y duradera","Seguro para todo tipo de pestañas gracias a su fórmula hipoalergénica","Fácil aplicación con resultados profesionales"}', includes = '{"Crema Lash Lifting","Crema Fijadora","Loción Limpiadora","Loción Vitaminada","Pigmento para Pestañas","Reactor para pigmento","Gel Reestructurante","5 Lifting Pads (SS, S, M, L, LL)","Adhesivo para pads","Máscara en Gel Acondicionadora","20 Protectores de Párpados","10 Aplicadores con espátula","4 Microcepillos","4 Cepillos para Pestañas","2 Anillos","10 Contenedores"}', performance = 'Hasta 35 aplicaciones', related_categories = '{"Lash Lifting","Tratamientos"}', original_price = 950, name = 'Kit Lash Lifting Profesional J.Denis', price = 850, category = 'Lash Lifting', compare_at_price = 950, is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('blue-lash-lifting', 'BLUE Lash Lifting', 500, 600, 'https://acdn-us.mitiendanube.com/stores/694/809/products/blue_mesa-de-trabajo-11-9092542207219bc30316691308859785-1024-1024.webp', 'Lash Lifting', true, 'Kit profesional de Lash Lifting BLUE con rendimiento extendido. Incluye pads de silicón reutilizables y geles de alta calidad para un lifting perfecto.', '{"Rendimiento extendido para mayor rentabilidad","Pads de silicón reutilizables","Geles de alta calidad profesional","Resultados naturales y duraderos"}', '{"Gel Ondulante BLUE","Gel Neutralizante BLUE","Gel Reestructurante","Pads de silicón reutilizables (varios tamaños)","Adhesivo para rulos BLUE","Limpiador de Impurezas BLUE","Herramientas de aplicación"}', 'Hasta 60 aplicaciones', '{}', '{}', NULL, '{"Lash Lifting"}', 600, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit profesional de Lash Lifting BLUE con rendimiento extendido. Incluye pads de silicón reutilizables y geles de alta calidad para un lifting perfecto.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/blue_mesa-de-trabajo-11-9092542207219bc30316691308859785-1024-1024.webp', benefits = '{"Rendimiento extendido para mayor rentabilidad","Pads de silicón reutilizables","Geles de alta calidad profesional","Resultados naturales y duraderos"}', includes = '{"Gel Ondulante BLUE","Gel Neutralizante BLUE","Gel Reestructurante","Pads de silicón reutilizables (varios tamaños)","Adhesivo para rulos BLUE","Limpiador de Impurezas BLUE","Herramientas de aplicación"}', performance = 'Hasta 60 aplicaciones', related_categories = '{"Lash Lifting"}', original_price = 600, name = 'BLUE Lash Lifting', price = 500, category = 'Lash Lifting', compare_at_price = 600, is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('crema-lifting-paso-1', 'Crema Lash Lifting', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/lifind-031-646dca838619ceeaa016687969981669-1024-1024.webp', 'Lash Lifting', false, 'Paso inicial (1) para el moldeado químico del vello. Fórmula hipoalergénica con pH controlado que suaviza la estructura del cabello para lograr la nueva forma deseada.', '{}', '{}', NULL, '{"Paso 1 del sistema Lash Lifting","pH controlado","Fórmula hipoalergénica","Para uso profesional"}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paso inicial (1) para el moldeado químico del vello. Fórmula hipoalergénica con pH controlado que suaviza la estructura del cabello para lograr la nueva forma deseada.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/lifind-031-646dca838619ceeaa016687969981669-1024-1024.webp', specifications = '{"Paso 1 del sistema Lash Lifting","pH controlado","Fórmula hipoalergénica","Para uso profesional"}', related_categories = '{"Lash Lifting"}', name = 'Crema Lash Lifting', price = 100, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('crema-fijadora-paso-2', 'Crema Lash Lifting Fijadora', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/lifind-041-e3cde4a2a43cc5e8cd16687971742837-1024-1024.webp', 'Lash Lifting', false, 'Paso final (2) con pH controlado para sellar la nueva forma sin dañar la cutícula. Fija el rizo de forma permanente y duradera.', '{}', '{}', NULL, '{"Paso 2 del sistema Lash Lifting","pH controlado","Sella sin dañar la cutícula","Fijación permanente"}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paso final (2) con pH controlado para sellar la nueva forma sin dañar la cutícula. Fija el rizo de forma permanente y duradera.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/lifind-041-e3cde4a2a43cc5e8cd16687971742837-1024-1024.webp', specifications = '{"Paso 2 del sistema Lash Lifting","pH controlado","Sella sin dañar la cutícula","Fijación permanente"}', related_categories = '{"Lash Lifting"}', name = 'Crema Lash Lifting Fijadora', price = 100, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-pads-lifting', 'Adhesivo Individual para Pads - Lifting', 380, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind_mesa-de-trabajo-11-dfc574ad69672ed3c216687966538196-1024-1024.webp', 'Lash Lifting', false, 'Adhesivo individual especializado para pads de lifting. Fijación precisa y segura para procedimientos profesionales de lash lifting.', '{}', '{}', NULL, '{"Fijación precisa para pads","Uso profesional","Compatible con todos los pads J.Denis"}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo individual especializado para pads de lifting. Fijación precisa y segura para procedimientos profesionales de lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind_mesa-de-trabajo-11-dfc574ad69672ed3c216687966538196-1024-1024.webp', specifications = '{"Fijación precisa para pads","Uso profesional","Compatible con todos los pads J.Denis"}', related_categories = '{"Lash Lifting"}', name = 'Adhesivo Individual para Pads - Lifting', price = 380, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('peine-lash-lifting', 'Peine para Lash Lifting', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', 'Lash Lifting', false, 'Peine profesional diseñado específicamente para procedimientos de lash lifting. Permite separar y distribuir las pestañas de forma uniforme sobre el pad.', '{}', '{}', NULL, '{"Diseño ergonómico","Dientes finos de precisión","Ideal para separar pestañas sobre el pad"}', '{}', NULL, '{"Lash Lifting","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Peine profesional diseñado específicamente para procedimientos de lash lifting. Permite separar y distribuir las pestañas de forma uniforme sobre el pad.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p31-c7c6e6930d4fa2037915872659858026-1024-1024.webp', specifications = '{"Diseño ergonómico","Dientes finos de precisión","Ideal para separar pestañas sobre el pad"}', related_categories = '{"Lash Lifting","Herramientas"}', name = 'Peine para Lash Lifting', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-rosas-micro-canales', 'Pad Rosas con Micro Canales', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', 'Lash Lifting', false, 'Pads de silicón premium con micro canales que facilitan la separación y elevación de las pestañas. Tecnología avanzada para resultados uniformes y profesionales.', '{"Micro canales para mejor separación de pestañas","Silicón de alta calidad reutilizable","Múltiples tamaños en un paquete","Fácil limpieza y desinfección"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pads de silicón premium con micro canales que facilitan la separación y elevación de las pestañas. Tecnología avanzada para resultados uniformes y profesionales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/r31-2113caa06848677a7f15872659444717-1024-1024.webp', benefits = '{"Micro canales para mejor separación de pestañas","Silicón de alta calidad reutilizable","Múltiples tamaños en un paquete","Fácil limpieza y desinfección"}', related_categories = '{"Lash Lifting"}', name = 'Pad Rosas con Micro Canales', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-nube', 'Pad Nube', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2019-02-09-a-las-20-04-021-39c0aa667e05a80ed715497643400355-1024-1024.webp', 'Lash Lifting', false, 'Pad ultra suave con forma de nube para lash lifting. Diseño ergonómico que se adapta a la curvatura natural del párpado para resultados perfectos.', '{"Forma ergonómica tipo nube","Ultra suave para máximo confort","Se adapta a la curvatura del párpado"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad ultra suave con forma de nube para lash lifting. Diseño ergonómico que se adapta a la curvatura natural del párpado para resultados perfectos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2019-02-09-a-las-20-04-021-39c0aa667e05a80ed715497643400355-1024-1024.webp', benefits = '{"Forma ergonómica tipo nube","Ultra suave para máximo confort","Se adapta a la curvatura del párpado"}', related_categories = '{"Lash Lifting"}', name = 'Pad Nube', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-anime', 'Pad Anime', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/anime-05-6e0e314c9e7228afe817410095004166-1024-1024.webp', 'Lash Lifting', false, 'Pad especial estilo Anime para crear un efecto de pestañas ultra abiertas y dramáticas. Ideal para looks artísticos y dramáticos.', '{"Efecto de pestañas ultra abiertas","Look dramático estilo anime","Silicón de alta calidad","Reutilizable"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad especial estilo Anime para crear un efecto de pestañas ultra abiertas y dramáticas. Ideal para looks artísticos y dramáticos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/anime-05-6e0e314c9e7228afe817410095004166-1024-1024.webp', benefits = '{"Efecto de pestañas ultra abiertas","Look dramático estilo anime","Silicón de alta calidad","Reutilizable"}', related_categories = '{"Lash Lifting"}', name = 'Pad Anime', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('kit-brow-henna', 'Brow Henna', 1200, 1400, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', 'Brow Henna', true, 'Una alternativa natural para sombrear las cejas. Derivado de la planta de Henna, en 30 minutos deja un efecto de tatuaje en la piel y recubre el vello de las cejas dando una apariencia de mayor abundancia. No contiene amoniaco, plomo, ni peróxido.', '{"Efecto tatuaje natural en la piel","Sin amoniaco, plomo ni peróxido","Mayor apariencia de abundancia en cejas","Duración de 3 a 10 días según cuidado","Alternativa no invasiva al microblading"}', '{"Henna Castaño Obscuro (30 aplicaciones)","Henna Castaño Medio (30 aplicaciones)","Henna Castaño Claro (30 aplicaciones)","Primer exfoliante para cejas","Activador para polvo Henna","Regla de 20 cm","Lápiz para diseño de cejas","Recipiente mezclador","6 Plantillas para cejas","4 Cepillos para cejas","4 Microbrush","3 Perfiladores para delinear"}', 'Hasta 90 aplicaciones totales (30 por tono)', '{}', '{}', NULL, '{"Brow Henna","Diseño de Cejas"}', 1400, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Una alternativa natural para sombrear las cejas. Derivado de la planta de Henna, en 30 minutos deja un efecto de tatuaje en la piel y recubre el vello de las cejas dando una apariencia de mayor abundancia. No contiene amoniaco, plomo, ni peróxido.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', benefits = '{"Efecto tatuaje natural en la piel","Sin amoniaco, plomo ni peróxido","Mayor apariencia de abundancia en cejas","Duración de 3 a 10 días según cuidado","Alternativa no invasiva al microblading"}', includes = '{"Henna Castaño Obscuro (30 aplicaciones)","Henna Castaño Medio (30 aplicaciones)","Henna Castaño Claro (30 aplicaciones)","Primer exfoliante para cejas","Activador para polvo Henna","Regla de 20 cm","Lápiz para diseño de cejas","Recipiente mezclador","6 Plantillas para cejas","4 Cepillos para cejas","4 Microbrush","3 Perfiladores para delinear"}', performance = 'Hasta 90 aplicaciones totales (30 por tono)', related_categories = '{"Brow Henna","Diseño de Cejas"}', original_price = 1400, name = 'Brow Henna', price = 1200, category = 'Brow Henna', compare_at_price = 1400, is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('activador-henna', 'Activador de Henna', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/activador-henna-2-2398d7caec1193296817558879257390-1024-1024.webp', 'Brow Henna', false, 'Activador líquido esencial para la preparación del polvo de henna. Contenido de 50 ml. Mezclado con el polvo de henna, permite obtener la consistencia perfecta para la aplicación.', '{}', '{}', NULL, '{"Contenido: 50 ml","Compatible con todos los polvos Henna J.Denis","Fácil dosificación"}', '{}', NULL, '{"Brow Henna"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Activador líquido esencial para la preparación del polvo de henna. Contenido de 50 ml. Mezclado con el polvo de henna, permite obtener la consistencia perfecta para la aplicación.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/activador-henna-2-2398d7caec1193296817558879257390-1024-1024.webp', specifications = '{"Contenido: 50 ml","Compatible con todos los polvos Henna J.Denis","Fácil dosificación"}', related_categories = '{"Brow Henna"}', name = 'Activador de Henna', price = 100, category = 'Brow Henna', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('henna-directa-brown', 'Henna Directa', 370, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', 'Brow Henna', false, 'Henna de aplicación directa sin mezcla compleja. Disponible en Medium Brown, Dark Brown y Black. Fórmula lista para usar con resultados inmediatos.', '{"Aplicación directa sin mezclas","Disponible en 3 tonos","Resultados inmediatos","Fácil de usar"}', '{}', NULL, '{}', '{}', NULL, '{"Brow Henna"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Henna de aplicación directa sin mezcla compleja. Disponible en Medium Brown, Dark Brown y Black. Fórmula lista para usar con resultados inmediatos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brow-henna-061-fbdb257619cce9e95d16669249148944-1024-1024.webp', benefits = '{"Aplicación directa sin mezclas","Disponible en 3 tonos","Resultados inmediatos","Fácil de usar"}', related_categories = '{"Brow Henna"}', name = 'Henna Directa', price = 370, category = 'Brow Henna', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('arco-diseno-cejas', 'Arco para Diseño de Cejas', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/arco-hilo_000131-98d2fedde55c00a63616035616219256-1024-1024.webp', 'Diseño de Cejas', false, 'Arco profesional para diseño y medición perfecta de cejas. Herramienta esencial para simetría y proporción en el diseño profesional.', '{}', '{}', NULL, '{"Material de alta durabilidad","Mediciones precisas","Ideal para diseño simétrico"}', '{}', NULL, '{"Diseño de Cejas","Herramientas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Arco profesional para diseño y medición perfecta de cejas. Herramienta esencial para simetría y proporción en el diseño profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/arco-hilo_000131-98d2fedde55c00a63616035616219256-1024-1024.webp', specifications = '{"Material de alta durabilidad","Mediciones precisas","Ideal para diseño simétrico"}', related_categories = '{"Diseño de Cejas","Herramientas"}', name = 'Arco para Diseño de Cejas', price = 200, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lapiz-cera', 'Lápiz de Cera', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mesa-de-trabajo-21-5623fc474fe25629fd16687989657552-1024-1024.webp', 'Diseño de Cejas', false, 'Lápiz de cera profesional para delinear y diseñar cejas con precisión. Trazo suave y definido que marca el diseño deseado antes del procedimiento.', '{}', '{}', NULL, '{"Trazo suave y preciso","Ideal para marcar diseño","Fácil de limpiar"}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Lápiz de cera profesional para delinear y diseñar cejas con precisión. Trazo suave y definido que marca el diseño deseado antes del procedimiento.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mesa-de-trabajo-21-5623fc474fe25629fd16687989657552-1024-1024.webp', specifications = '{"Trazo suave y preciso","Ideal para marcar diseño","Fácil de limpiar"}', related_categories = '{"Diseño de Cejas"}', name = 'Lápiz de Cera', price = 70, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('laminado-cejas', 'Laminado de Cejas', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/diseno-021-ca4a861d525c316b2d16669243762302-1024-1024.webp', 'Diseño de Cejas', true, 'Sistema para moldear y fijar cejas rebeldes. Logra un efecto de cejas perfectamente peinadas y disciplinadas con resultados duraderos.', '{"Moldea cejas rebeldes","Efecto de cejas perfectamente peinadas","Fijación duradera","Resultados profesionales"}', '{"Gel Planchador","Gel Fijador","Gel Reestructurante","Cepillos para cejas"}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas","Brow Henna"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Sistema para moldear y fijar cejas rebeldes. Logra un efecto de cejas perfectamente peinadas y disciplinadas con resultados duraderos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/diseno-021-ca4a861d525c316b2d16669243762302-1024-1024.webp', benefits = '{"Moldea cejas rebeldes","Efecto de cejas perfectamente peinadas","Fijación duradera","Resultados profesionales"}', includes = '{"Gel Planchador","Gel Fijador","Gel Reestructurante","Cepillos para cejas"}', related_categories = '{"Diseño de Cejas","Brow Henna"}', name = 'Laminado de Cejas', price = 200, category = 'Diseño de Cejas', is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tintura-topica-castano-medio', 'Tintura Tópica - Castaño Medio', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pigmento-light-brown-31-5d8c78b2d2ba43be9e16671823980793-1024-1024.webp', 'Pigmentos', false, 'Tintura tópica profesional tono castaño medio para pestañas y cejas. Color natural y duradero ideal para clientas con tono de cabello medio.', '{}', '{}', NULL, '{"Tono: Castaño Medio","Para cejas y pestañas","Fórmula profesional","Larga duración"}', '{}', NULL, '{"Pigmentos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tintura tópica profesional tono castaño medio para pestañas y cejas. Color natural y duradero ideal para clientas con tono de cabello medio.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pigmento-light-brown-31-5d8c78b2d2ba43be9e16671823980793-1024-1024.webp', specifications = '{"Tono: Castaño Medio","Para cejas y pestañas","Fórmula profesional","Larga duración"}', related_categories = '{"Pigmentos","Lash Lifting"}', name = 'Tintura Tópica - Castaño Medio', price = 100, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tintura-topica-castano-oscuro', 'Tintura Tópica - Castaño Oscuro', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pig-071-10ea3ab254a18fa68516691314001398-1024-1024.webp', 'Pigmentos', false, 'Tintura tópica profesional tono castaño oscuro para pestañas y cejas. Color intenso y duradero ideal para clientas con tono de cabello oscuro.', '{}', '{}', NULL, '{"Tono: Castaño Oscuro","Color intenso y duradero","Para cejas y pestañas","Fórmula profesional"}', '{}', NULL, '{"Pigmentos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tintura tópica profesional tono castaño oscuro para pestañas y cejas. Color intenso y duradero ideal para clientas con tono de cabello oscuro.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pig-071-10ea3ab254a18fa68516691314001398-1024-1024.webp', specifications = '{"Tono: Castaño Oscuro","Color intenso y duradero","Para cejas y pestañas","Fórmula profesional"}', related_categories = '{"Pigmentos","Lash Lifting"}', name = 'Tintura Tópica - Castaño Oscuro', price = 150, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pigmento-pestanas', 'Pigmento para Pestañas', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pigmento-pestanas-21-75321496155008e18a16671825880489-1024-1024.webp', 'Pigmentos', false, 'Pigmento negro puro con keratina para tinturar pestañas. Fórmula enriquecida que colorea y fortalece al mismo tiempo.', '{"Color negro puro intenso","Enriquecido con keratina","Colorea y fortalece","Resultados profesionales duraderos"}', '{"Pigmento negro con keratina","Reactor para pigmento","Protectores de párpados"}', NULL, '{}', '{}', NULL, '{"Pigmentos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pigmento negro puro con keratina para tinturar pestañas. Fórmula enriquecida que colorea y fortalece al mismo tiempo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pigmento-pestanas-21-75321496155008e18a16671825880489-1024-1024.webp', benefits = '{"Color negro puro intenso","Enriquecido con keratina","Colorea y fortalece","Resultados profesionales duraderos"}', includes = '{"Pigmento negro con keratina","Reactor para pigmento","Protectores de párpados"}', related_categories = '{"Pigmentos","Lash Lifting"}', name = 'Pigmento para Pestañas', price = 200, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('chocolate-pigmento-cejas', 'Chocolate Pigmento para Cejas', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-4_mesa-de-trabajo-111-c242d37fa4b290473b16687990494212-1024-1024.webp', 'Pigmentos', false, 'Pigmento tono chocolate para cejas. Color cálido y natural que se adapta a diversos tonos de piel y cabello. Ideal para un look natural y sofisticado.', '{}', '{}', NULL, '{"Tono: Chocolate","Color cálido y natural","Para cejas","Compatible con Brow Henna"}', '{}', NULL, '{"Pigmentos","Brow Henna"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pigmento tono chocolate para cejas. Color cálido y natural que se adapta a diversos tonos de piel y cabello. Ideal para un look natural y sofisticado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-4_mesa-de-trabajo-111-c242d37fa4b290473b16687990494212-1024-1024.webp', specifications = '{"Tono: Chocolate","Color cálido y natural","Para cejas","Compatible con Brow Henna"}', related_categories = '{"Pigmentos","Brow Henna"}', name = 'Chocolate Pigmento para Cejas', price = 200, category = 'Pigmentos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('jade-rizado-pestanas', 'JADE Rizado de Pestañas', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/rizado-jade-11-ac3bb9dfd4f533b09316671818885563-1024-1024.webp', 'Lash Curling', true, 'Kit completo para rizado permanente de pestañas. Sistema profesional que crea una curvatura natural y duradera en las pestañas naturales.', '{"Rizado permanente natural","Kit completo listo para usar","Fórmula suave y segura","Resultados profesionales"}', '{"Adhesivo para rizado","Gel ondulante","Gel neutralizante","Rulos en diferentes tamaños","Herramientas de aplicación"}', 'Hasta 30 aplicaciones', '{}', '{}', NULL, '{"Lash Curling","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Kit completo para rizado permanente de pestañas. Sistema profesional que crea una curvatura natural y duradera en las pestañas naturales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/rizado-jade-11-ac3bb9dfd4f533b09316671818885563-1024-1024.webp', benefits = '{"Rizado permanente natural","Kit completo listo para usar","Fórmula suave y segura","Resultados profesionales"}', includes = '{"Adhesivo para rizado","Gel ondulante","Gel neutralizante","Rulos en diferentes tamaños","Herramientas de aplicación"}', performance = 'Hasta 30 aplicaciones', related_categories = '{"Lash Curling","Lash Lifting"}', name = 'JADE Rizado de Pestañas', price = 250, category = 'Lash Curling', is_featured = true, updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-desechables-m', 'Rulos Desechables Curva Media M', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-041-c63eba028c157f5cb716669736468826-1024-1024.webp', 'Lash Curling', false, 'Rulos desechables de curva media tamaño M. Ideales para crear una curvatura natural y elegante en pestañas de longitud media.', '{}', '{}', NULL, '{"Tamaño: M (Curva Media)","Desechables para máxima higiene","Silicón de alta calidad"}', '{}', NULL, '{"Lash Curling","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos desechables de curva media tamaño M. Ideales para crear una curvatura natural y elegante en pestañas de longitud media.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-041-c63eba028c157f5cb716669736468826-1024-1024.webp', specifications = '{"Tamaño: M (Curva Media)","Desechables para máxima higiene","Silicón de alta calidad"}', related_categories = '{"Lash Curling","Lash Lifting"}', name = 'Rulos Desechables Curva Media M', price = 50, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-desechables-ch', 'Rulos Desechables Curva Corta CH', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-1024-1024.webp', 'Lash Curling', false, 'Rulos desechables de curva corta tamaño CH. Ideales para pestañas cortas o para crear una curvatura más dramática.', '{}', '{}', NULL, '{"Tamaño: CH (Curva Corta)","Desechables para máxima higiene","Ideal para pestañas cortas"}', '{}', NULL, '{"Lash Curling","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos desechables de curva corta tamaño CH. Ideales para pestañas cortas o para crear una curvatura más dramática.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-1024-1024.webp', specifications = '{"Tamaño: CH (Curva Corta)","Desechables para máxima higiene","Ideal para pestañas cortas"}', related_categories = '{"Lash Curling","Lash Lifting"}', name = 'Rulos Desechables Curva Corta CH', price = 50, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-desechables-g', 'Rulos Desechables Curva Amplia G', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1_mesa-de-trabajo-11-f490e5702841a57b1616669735647217-1024-1024.webp', 'Lash Curling', false, 'Rulos desechables de curva amplia tamaño G. Perfectos para pestañas largas o para un lifting más sutil y natural.', '{}', '{}', NULL, '{"Tamaño: G (Curva Amplia)","Desechables para máxima higiene","Ideal para pestañas largas"}', '{}', NULL, '{"Lash Curling","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos desechables de curva amplia tamaño G. Perfectos para pestañas largas o para un lifting más sutil y natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1_mesa-de-trabajo-11-f490e5702841a57b1616669735647217-1024-1024.webp', specifications = '{"Tamaño: G (Curva Amplia)","Desechables para máxima higiene","Ideal para pestañas largas"}', related_categories = '{"Lash Curling","Lash Lifting"}', name = 'Rulos Desechables Curva Amplia G', price = 50, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-adhesivos-curva-g', 'Rulos Adhesivos Curva G', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/53-rulos-adhesivos-031-2ade2563ab84da548d15314940318959-1024-1024.webp', 'Lash Curling', false, 'Rulos con adhesivo integrado curva G. Se adhieren directamente al párpado sin necesidad de adhesivo adicional. Reutilizables.', '{}', '{}', NULL, '{"Adhesivo integrado","Curva G (Amplia)","Reutilizables","Sin adhesivo adicional"}', '{}', NULL, '{"Lash Curling"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos con adhesivo integrado curva G. Se adhieren directamente al párpado sin necesidad de adhesivo adicional. Reutilizables.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/53-rulos-adhesivos-031-2ade2563ab84da548d15314940318959-1024-1024.webp', specifications = '{"Adhesivo integrado","Curva G (Amplia)","Reutilizables","Sin adhesivo adicional"}', related_categories = '{"Lash Curling"}', name = 'Rulos Adhesivos Curva G', price = 70, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-super-volume', 'Pestaña Super Volume', 380, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pestana-flat-6-67059c90c476666e3217112091825676-1024-1024.webp', 'Extensiones', false, 'Línea premium para técnicas de abanicos 2D a 6D. Máxima ligereza y suavidad. Ideal para volumen ruso con acabado profesional impecable.', '{"Ultra livianas para técnica de abanicos","Compatibles con técnicas 2D a 6D","Máxima suavidad y comodidad","Acabado profesional natural"}', '{}', NULL, '{"Técnica: Volumen ruso","Tipo: Super Volume","Material: Fibra PBT premium"}', '{}', NULL, '{"Extensiones","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Línea premium para técnicas de abanicos 2D a 6D. Máxima ligereza y suavidad. Ideal para volumen ruso con acabado profesional impecable.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pestana-flat-6-67059c90c476666e3217112091825676-1024-1024.webp', benefits = '{"Ultra livianas para técnica de abanicos","Compatibles con técnicas 2D a 6D","Máxima suavidad y comodidad","Acabado profesional natural"}', specifications = '{"Técnica: Volumen ruso","Tipo: Super Volume","Material: Fibra PBT premium"}', related_categories = '{"Extensiones","Adhesivos"}', name = 'Pestaña Super Volume', price = 380, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;