INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('curva-lc-010-combo', 'Curva LC | 0.10 | Mixta', 280, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/2d-0-15-b-101-ed1be18f240c6503c716337346424009-480-0.webp', 'Extensiones', false, 'Extensiones curva LC grosor 0.10 combo mixto.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva LC grosor 0.10 combo mixto.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/2d-0-15-b-101-ed1be18f240c6503c716337346424009-480-0.webp', related_categories = '{"Extensiones"}', name = 'Curva LC | 0.10 | Mixta', price = 280, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('curva-lc-015-combo', 'Curva LC | 0.15 | Mixta', 280, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/2d-0-15-b-101-ed1be18f240c6503c716337346424009-480-0.webp', 'Extensiones', false, 'Extensiones curva LC grosor 0.15 combo mixto.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones curva LC grosor 0.15 combo mixto.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/2d-0-15-b-101-ed1be18f240c6503c716337346424009-480-0.webp', related_categories = '{"Extensiones"}', name = 'Curva LC | 0.15 | Mixta', price = 280, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-abanicos-sin-punta', 'Pinza Abanicos sin Punta', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-punta-11-01f6336c5e77686f5b16275044778948-480-0.webp', 'Herramientas', false, 'Pinza para abanicos sin punta para extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza para abanicos sin punta para extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-punta-11-01f6336c5e77686f5b16275044778948-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Abanicos sin Punta', price = 100, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-ele-m19', 'Pinza Ele M-19', 140, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', 'Herramientas', false, 'Pinza profesional en forma de ele modelo M-19.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional en forma de ele modelo M-19.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Ele M-19', price = 140, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-md14-ele', 'Pinza MD 14 en Ele', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/rnqo91301-301a1e5c1eb7c2d41016567718166121-480-0.webp', 'Herramientas', false, 'Pinza MD 14 en forma de ele para extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza MD 14 en forma de ele para extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/rnqo91301-301a1e5c1eb7c2d41016567718166121-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza MD 14 en Ele', price = 200, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-md14-punta', 'Pinza MD 14 en Punta', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/wpfs53581-363b5cfbc93b7d967216567716588826-480-0.webp', 'Herramientas', false, 'Pinza MD 14 en punta para extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza MD 14 en punta para extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/wpfs53581-363b5cfbc93b7d967216567716588826-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza MD 14 en Punta', price = 200, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-colocar-m18', 'Pinza para Colocar M-18', 140, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', 'Herramientas', false, 'Pinza para colocar extensiones modelo M-18.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza para colocar extensiones modelo M-18.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza para Colocar M-18', price = 140, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-depilar', 'Pinza para Depilar', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/con-peine-plata1-5bdd469dc6a19e888716274269228512-480-0.webp', 'Herramientas', false, 'Pinza profesional para depilar cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza profesional para depilar cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/con-peine-plata1-5bdd469dc6a19e888716274269228512-480-0.webp', related_categories = '{"Herramientas","Diseño de Cejas"}', name = 'Pinza para Depilar', price = 150, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-punta-larga', 'Pinza Punta Larga', 140, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', 'Herramientas', false, 'Pinza de punta larga para extensiones de pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza de punta larga para extensiones de pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Punta Larga', price = 140, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pinza-punta-m12', 'Pinza Punta M-12', 140, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', 'Herramientas', false, 'Pinza punta modelo M-12 para extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pinza punta modelo M-12 para extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-f73143c3262f6e86e317344090343101-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Pinza Punta M-12', price = 140, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-balsamo-30gr', 'Adhesivo Bálsamo Butter 30 gr', 380, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Adhesivos', false, 'Adhesivo bálsamo butter presentación de 30 gramos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo bálsamo butter presentación de 30 gramos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Bálsamo Butter 30 gr', price = 380, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('limpiador-impurezas-normal-seca', 'Limpiador de Impurezas | Piel Normal y Seca', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Higiene', false, 'Limpiador de impurezas formulado para piel normal y seca.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Limpiador de impurezas formulado para piel normal y seca.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Higiene","Lash Lifting"}', name = 'Limpiador de Impurezas | Piel Normal y Seca', price = 90, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tintura-topica-castano-oscuro', 'Tintura Tópica - Castaño Oscuro', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Tintura', false, 'Tintura tópica profesional color castaño oscuro para cejas y pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tintura"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tintura tópica profesional color castaño oscuro para cejas y pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Tintura"}', name = 'Tintura Tópica - Castaño Oscuro', price = 350, category = 'Tintura', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tintura-topica-negro', 'Tintura Tópica - Negro', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Tintura', false, 'Tintura tópica profesional color negro para cejas y pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tintura"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tintura tópica profesional color negro para cejas y pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Tintura"}', name = 'Tintura Tópica - Negro', price = 350, category = 'Tintura', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-adhesivos-curva-ch', 'Rulos Adhesivos Curva CH', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', 'Lash Lifting', false, 'Rulos adhesivos curva corta (CH) para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos adhesivos curva corta (CH) para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Rulos Adhesivos Curva CH', price = 70, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-adhesivos-curva-m', 'Rulos Adhesivos Curva M', 70, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', 'Lash Lifting', false, 'Rulos adhesivos curva media (M) para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos adhesivos curva media (M) para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Rulos Adhesivos Curva M', price = 70, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-desechables-ch', 'Rulos Desechables Curva Corta CH', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', 'Lash Lifting', false, 'Rulos desechables curva corta (CH) para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos desechables curva corta (CH) para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Rulos Desechables Curva Corta CH', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('rulos-desechables-g', 'Rulos Desechables Curva Amplia G', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', 'Lash Lifting', false, 'Rulos desechables curva amplia (G) para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Rulos desechables curva amplia (G) para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-1-071-f0552b059105e2a53d16669736033613-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Rulos Desechables Curva Amplia G', price = 50, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;