INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('mica-cubre-boca', 'Mica Cubre Boca', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mica1-1ead16074c150b7c3f15494014566587-1024-1024.webp', 'Higiene', false, 'Mica transparente cubre boca para protección durante procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Mica transparente cubre boca para protección durante procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mica1-1ead16074c150b7c3f15494014566587-1024-1024.webp', related_categories = '{"Higiene"}', name = 'Mica Cubre Boca', price = 50, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('guantes-nitrilo', 'Guantes de Nitrilo', 390, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/5f19357c6ed20-ebd48acb-d3e2-4457-994f-5637326cd14b-1600x16001-9cfda1c2e5b7e63dcf16034906790930-1024-1024.webp', 'Higiene', false, 'Guantes de nitrilo profesional. Disponible en talla chica, mediana y grande.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Higiene"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Guantes de nitrilo profesional. Disponible en talla chica, mediana y grande.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/5f19357c6ed20-ebd48acb-d3e2-4457-994f-5637326cd14b-1600x16001-9cfda1c2e5b7e63dcf16034906790930-1024-1024.webp', related_categories = '{"Higiene"}', name = 'Guantes de Nitrilo', price = 390, category = 'Higiene', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pulsera-base-medidas', 'Pulsera Base con Medidas', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', 'Accesorios', false, 'Pulsera con base y medidas para apoyo durante procedimientos de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pulsera con base y medidas para apoyo durante procedimientos de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-1024-1024.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Pulsera Base con Medidas', price = 100, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('fijador-maquillaje', 'Fijador de Maquillaje', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-1024-1024.webp', 'Accesorios', false, 'Fijador de maquillaje en spray para prolongar la duración del maquillaje.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Fijador de maquillaje en spray para prolongar la duración del maquillaje.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/bifasico_mesa-de-trabajo-1-6eb4be9674069796fb17344099355972-1024-1024.webp', related_categories = '{"Accesorios"}', name = 'Fijador de Maquillaje', price = 50, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('cinta-adhesiva-colores', 'Cinta Adhesiva (Colores)', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-plastico11-a71209ec9ed985a90016034886124545-1024-1024.webp', 'Accesorios', false, 'Cinta adhesiva en colores para protección durante procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cinta adhesiva en colores para protección durante procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-plastico11-a71209ec9ed985a90016034886124545-1024-1024.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Cinta Adhesiva (Colores)', price = 50, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('sticker-reutilizable-parpado', 'Sticker Reutilizable para Párpado', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/parpado-021-4abf45055504f2086716692331225943-1024-1024.webp', 'Accesorios', false, 'Sticker reutilizable para protección de párpado durante procedimientos.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Sticker reutilizable para protección de párpado durante procedimientos.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/parpado-021-4abf45055504f2086716692331225943-1024-1024.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Sticker Reutilizable para Párpado', price = 50, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('lash-ribbon', 'Lash Ribbon', 50, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-microfoam11-8f139166d09bc9572916034888094159-1024-1024.webp', 'Accesorios', false, 'Cinta para pestañas lash ribbon para separación y protección.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Cinta para pestañas lash ribbon para separación y protección.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/cinta-microfoam11-8f139166d09bc9572916034888094159-1024-1024.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Lash Ribbon', price = 50, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('glue-less-powder', 'Glue Less Powder', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/shaker_mesa-de-trabajo-1-copia-4e0418ae0983baf4f617344074504573-1024-1024.webp', 'Accesorios', false, 'Polvo para mejorar la retención del adhesivo. Optimiza el secado.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Adhesivos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Polvo para mejorar la retención del adhesivo. Optimiza el secado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/shaker_mesa-de-trabajo-1-copia-4e0418ae0983baf4f617344074504573-1024-1024.webp', related_categories = '{"Accesorios","Adhesivos"}', name = 'Glue Less Powder', price = 150, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('air-pump', 'Air Pump', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/54-air-pump-04-0111-ee7967faab158a16a715314972504963-1024-1024.webp', 'Accesorios', false, 'Bomba de aire para secado rápido del adhesivo de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Accesorios","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Bomba de aire para secado rápido del adhesivo de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/54-air-pump-04-0111-ee7967faab158a16a715314972504963-1024-1024.webp', related_categories = '{"Accesorios","Extensiones"}', name = 'Air Pump', price = 100, category = 'Accesorios', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tratamiento-capilar-ph4', 'Tratamiento Capilar pH 4', 75, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-1024-1024.webp', 'Tratamientos', false, 'Tratamiento capilar con pH 4 para nutrición y reestructuración.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tratamiento capilar con pH 4 para nutrición y reestructuración.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-1024-1024.webp', related_categories = '{"Tratamientos"}', name = 'Tratamiento Capilar pH 4', price = 75, category = 'Tratamientos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('botox-pestanas', 'Botox Pestañas', 200, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-1024-1024.webp', 'Tratamientos', false, 'Tratamiento botox para pestañas. Nutre, engrosa y fortalece desde la raíz.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tratamientos","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tratamiento botox para pestañas. Nutre, engrosa y fortalece desde la raíz.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-30-a-las-19-57-071-04021a75d3be481cba16671814910615-1024-1024.webp', related_categories = '{"Tratamientos","Lash Lifting"}', name = 'Botox Pestañas', price = 200, category = 'Tratamientos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('after-care-microblading', 'After Care', 500, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', 'Microblading', false, 'Tratamiento After Care para post-procedimiento de microblading.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Microblading"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tratamiento After Care para post-procedimiento de microblading.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/vitamina-011-556c65fa50decd1e2a15494016039704-1024-1024.webp', related_categories = '{"Microblading"}', name = 'After Care', price = 500, category = 'Microblading', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('limpiador-impurezas-blue', 'Limpiador de Impurezas - Blue', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-031-3e42554c91778a025516687967769318-480-0.webp', 'Lash Curling', false, 'Preparador para la zona de ojos, elimina grasa e impurezas antes de aplicar procedimientos de rizado o extensiones.', '{"Mejora la adherencia de los productos"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Curling","Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Preparador para la zona de ojos, elimina grasa e impurezas antes de aplicar procedimientos de rizado o extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-031-3e42554c91778a025516687967769318-480-0.webp', benefits = '{"Mejora la adherencia de los productos"}', related_categories = '{"Lash Curling","Lash Lifting"}', name = 'Limpiador de Impurezas - Blue', price = 60, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-rulos-blue', 'Adhesivo para Rulos - Blue', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind_mesa-de-trabajo-11-dfc574ad69672ed3c216687966538196-480-0.webp', 'Lash Curling', false, 'Adhesivo especializado para fijar rulos durante el proceso de rizado de pestañas línea Blue.', '{"Fijación precisa","Fácil de limpiar"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Curling"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo especializado para fijar rulos durante el proceso de rizado de pestañas línea Blue.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind_mesa-de-trabajo-11-dfc574ad69672ed3c216687966538196-480-0.webp', benefits = '{"Fijación precisa","Fácil de limpiar"}', related_categories = '{"Lash Curling"}', name = 'Adhesivo para Rulos - Blue', price = 60, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('gel-ondulante-blue', 'Gel Ondulante - Blue', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-041-0b50e932a81e17ebed16687967632100-480-0.webp', 'Lash Curling', false, 'Paso 1 para el rizado de pestañas línea Blue. Permite moldear la fibra capilar.', '{"Acción rápida","Resultados duraderos"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Curling"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paso 1 para el rizado de pestañas línea Blue. Permite moldear la fibra capilar.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-041-0b50e932a81e17ebed16687967632100-480-0.webp', benefits = '{"Acción rápida","Resultados duraderos"}', related_categories = '{"Lash Curling"}', name = 'Gel Ondulante - Blue', price = 90, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('gel-neutralizante-blue', 'Gel Neutralizante - Blue', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-051-6de996f39be86e521716687967109859-480-0.webp', 'Lash Curling', false, 'Paso 2 para el rizado de pestañas línea Blue. Fija la forma ondulada deseada.', '{"Estabiliza el proceso químico"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Curling"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paso 2 para el rizado de pestañas línea Blue. Fija la forma ondulada deseada.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-051-6de996f39be86e521716687967109859-480-0.webp', benefits = '{"Estabiliza el proceso químico"}', related_categories = '{"Lash Curling"}', name = 'Gel Neutralizante - Blue', price = 90, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('gel-reestructurante-blue', 'Gel Reestructurante - Blue', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-480-0.webp', 'Lash Curling', false, 'Gel para hidratar y fortalecer las pestañas después del rizado línea Blue.', '{"Nutre y suaviza la pestaña"}', '{}', NULL, '{}', '{}', NULL, '{"Lash Curling"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Gel para hidratar y fortalecer las pestañas después del rizado línea Blue.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/ind-061-2e3f5f8fbac4155cb516687966859946-480-0.webp', benefits = '{"Nutre y suaviza la pestaña"}', related_categories = '{"Lash Curling"}', name = 'Gel Reestructurante - Blue', price = 60, category = 'Lash Curling', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-transparente-tira-ihi', 'Adhesivo Transparente Pestañas en Tira IHI', 40, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', 'Adhesivos', false, 'Adhesivo transparente para pestañas de tira. Brinda una fijación segura y discreta.', '{"Invisible al secar","Larga duración"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo transparente para pestañas de tira. Brinda una fijación segura y discreta.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', benefits = '{"Invisible al secar","Larga duración"}', related_categories = '{"Adhesivos","Pestañas en Tira"}', name = 'Adhesivo Transparente Pestañas en Tira IHI', price = 40, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-obscuro-tira-ihi', 'Adhesivo Obscuro Pestañas en Tira IHI', 40, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', 'Adhesivos', false, 'Adhesivo negro para pestañas de tira. Efecto de delineado natural.', '{"Efecto delineado","Fijación fuerte"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo negro para pestañas de tira. Efecto de delineado natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', benefits = '{"Efecto delineado","Fijación fuerte"}', related_categories = '{"Adhesivos","Pestañas en Tira"}', name = 'Adhesivo Obscuro Pestañas en Tira IHI', price = 40, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-negro-grupo', 'Adhesivo Negro - Pestañas en Grupo', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/kerat-021-36b8dbd9c51caa6a6a16691318586913-480-0.webp', 'Adhesivos', false, 'Adhesivo especializado para pestañas en grupo. Tono negro para un efecto de delineado.', '{"Secado rápido","Tono negro intenso"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo especializado para pestañas en grupo. Tono negro para un efecto de delineado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/kerat-021-36b8dbd9c51caa6a6a16691318586913-480-0.webp', benefits = '{"Secado rápido","Tono negro intenso"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Negro - Pestañas en Grupo', price = 60, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-transparente-grupo', 'Adhesivo Transparente - Pestañas en Grupo', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/kerat-061-5e6f566b3df2fabc7e16691319066677-480-0.webp', 'Adhesivos', false, 'Adhesivo transparente de alta fijación para pestañas en grupo o individuales de nudo.', '{"Fijación fuerte","Acabado natural"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo transparente de alta fijación para pestañas en grupo o individuales de nudo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/kerat-061-5e6f566b3df2fabc7e16691319066677-480-0.webp', benefits = '{"Fijación fuerte","Acabado natural"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Transparente - Pestañas en Grupo', price = 60, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('quitapestanas-liquido-grupo', 'Quitapestañas Líquido - Pestañas en Grupo', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/quit-061-2d6795ce0280cfc02c16691323314869-480-0.webp', 'Adhesivos', false, 'Líquido para remover adhesivos de pestañas en grupo de manera segura sin dañar la pestaña natural.', '{"Remoción suave y rápida"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Líquido para remover adhesivos de pestañas en grupo de manera segura sin dañar la pestaña natural.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/quit-061-2d6795ce0280cfc02c16691323314869-480-0.webp', benefits = '{"Remoción suave y rápida"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Quitapestañas Líquido - Pestañas en Grupo', price = 60, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-latex-transparente', 'Adhesivo Libre de Látex - Transparente', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', 'Adhesivos', false, 'Adhesivo transparente libre de látex para pieles sensibles.', '{"Hipoalergénico","Secado transparente"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo transparente libre de látex para pieles sensibles.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', benefits = '{"Hipoalergénico","Secado transparente"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Libre de Látex - Transparente', price = 90, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('adhesivo-latex-blanco', 'Adhesivo Libre de Látex - Blanco', 90, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', 'Adhesivos', false, 'Adhesivo blanco libre de látex para pieles sensibles.', '{"Hipoalergénico","Alta fijación"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Adhesivo blanco libre de látex para pieles sensibles.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/adhesivo-ihi-transparente-3-47c2520f7d78dfe66617552053250344-480-0.webp', benefits = '{"Hipoalergénico","Alta fijación"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Adhesivo Libre de Látex - Blanco', price = 90, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('removedor-pink-gel', 'Removedor Pink Gel', 280, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/kerat-021-36b8dbd9c51caa6a6a16691318586913-480-0.webp', 'Adhesivos', false, 'Removedor en gel rosa para extensiones de pestañas. Remoción segura y gentil.', '{"No gotea","Remoción controlada"}', '{}', NULL, '{}', '{}', NULL, '{"Adhesivos","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Removedor en gel rosa para extensiones de pestañas. Remoción segura y gentil.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/kerat-021-36b8dbd9c51caa6a6a16691318586913-480-0.webp', benefits = '{"No gotea","Remoción controlada"}', related_categories = '{"Adhesivos","Extensiones"}', name = 'Removedor Pink Gel', price = 280, category = 'Adhesivos', updated_at = CURRENT_TIMESTAMP;