INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('maniqui-extensiones', 'Maniquí Práctica de Extensiones', 220, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Maniquí para práctica de extensiones de pestañas por profesionales.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Maniquí para práctica de extensiones de pestañas por profesionales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Maniquí Práctica de Extensiones', price = 220, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('almohada-estante-organizador', 'Almohada con Estante Organizador', 750, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', 'Herramientas', false, 'Almohada profesional con estante organizador integrado para procedimientos de extensiones.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Herramientas","Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Almohada profesional con estante organizador integrado para procedimientos de extensiones.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verni-081-c75fff1cc921fb9b2816691435265855-480-0.webp', related_categories = '{"Herramientas","Extensiones"}', name = 'Almohada con Estante Organizador', price = 750, category = 'Herramientas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('tatuaje-temporal-cejas', 'Tatuaje Temporal para Cejas', 60, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', 'Diseño de Cejas', false, 'Tatuaje temporal para diseño y prueba de forma de cejas antes de procedimiento permanente.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Tatuaje temporal para diseño y prueba de forma de cejas antes de procedimiento permanente.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', related_categories = '{"Diseño de Cejas"}', name = 'Tatuaje Temporal para Cejas', price = 60, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('perfilador-pocket-ceja', 'Perfilador Pocket para Ceja', 100, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', 'Diseño de Cejas', false, 'Perfilador compacto pocket para diseño de cejas portátil.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Diseño de Cejas"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Perfilador compacto pocket para diseño de cejas portátil.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/brows-fixative-3-bcbac541f8e9fb29f417589971064547-480-0.webp', related_categories = '{"Diseño de Cejas"}', name = 'Perfilador Pocket para Ceja', price = 100, category = 'Diseño de Cejas', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('sellador-tintura', 'Sellador para Tintura Tópica', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Tintura', false, 'Sellador profesional para tintura tópica de cejas y pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tintura"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Sellador profesional para tintura tópica de cejas y pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Tintura"}', name = 'Sellador para Tintura Tópica', price = 350, category = 'Tintura', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('activador-tintura', 'Activador para Tintura Tópica', 350, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', 'Tintura', false, 'Activador profesional para tintura tópica de cejas y pestañas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Tintura"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Activador profesional para tintura tópica de cejas y pestañas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2022-10-27-a-las-22-07-361-25ed0e1a59714d490e16669266380337-480-0.webp', related_categories = '{"Tintura"}', name = 'Activador para Tintura Tópica', price = 350, category = 'Tintura', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-2-en-1', 'Pad 2 en 1', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/pad-2en1-04-ca761e232e805d891e17410115760489-480-0.webp', 'Lash Lifting', false, 'Pad de silicón 2 en 1 para lash lifting profesional.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón 2 en 1 para lash lifting profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/pad-2en1-04-ca761e232e805d891e17410115760489-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad 2 en 1', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-anime', 'Pad Anime', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/anime-05-6e0e314c9e7228afe817410095004166-480-0.webp', 'Lash Lifting', false, 'Pad de silicón diseño Anime para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón diseño Anime para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/anime-05-6e0e314c9e7228afe817410095004166-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Anime', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-curva-c', 'Pad Curva C', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', 'Lash Lifting', false, 'Pad de silicón con curva C para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón con curva C para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Curva C', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-rosa-sin-canales', 'Pad Rosa sin Canales', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2021-04-20-a-las-12-51-361-31ffe5daf9b33aeaba16189411299706-480-0.webp', 'Lash Lifting', false, 'Pad rosa liso sin canales para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad rosa liso sin canales para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/captura-de-pantalla-2021-04-20-a-las-12-51-361-31ffe5daf9b33aeaba16189411299706-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Rosa sin Canales', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-superior-inferior', 'Pad Superior e Inferior', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/verdes-03-a758a450feb27d7f7617187363942632-480-0.webp', 'Lash Lifting', false, 'Set de pads para pestañas superiores e inferiores.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de pads para pestañas superiores e inferiores.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/verdes-03-a758a450feb27d7f7617187363942632-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Superior e Inferior', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-colors-8p', 'Pad Colors 8p', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/color8_mesa-de-trabajo-1-082794b81eb64ce0f317187370015350-480-0.webp', 'Lash Lifting', false, 'Set de 8 pads de colores para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de 8 pads de colores para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/color8_mesa-de-trabajo-1-082794b81eb64ce0f317187370015350-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Colors 8p', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-colors-6p', 'Pad Colors 6p', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/color6_mesa-de-trabajo-1-99c271f1e6277b582917187371558250-480-0.webp', 'Lash Lifting', false, 'Set de 6 pads de colores para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Set de 6 pads de colores para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/color6_mesa-de-trabajo-1-99c271f1e6277b582917187371558250-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Colors 6p', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-oso', 'Pad Oso', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/osos-03-f51e1dda485dee146d17410099492242-480-0.webp', 'Lash Lifting', false, 'Pad de silicón diseño Oso para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón diseño Oso para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/osos-03-f51e1dda485dee146d17410099492242-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Oso', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-corrector-reversion', 'Pad Corrector (Reversión)', 300, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', 'Lash Lifting', false, 'Pad corrector para reversión de lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad corrector para reversión de lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Corrector (Reversión)', price = 300, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-mariposa', 'Pad Mariposa', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/mariposa-05-764fa14cdfc67005ba17410124758679-480-0.webp', 'Lash Lifting', false, 'Pad de silicón diseño Mariposa para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón diseño Mariposa para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/mariposa-05-764fa14cdfc67005ba17410124758679-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Mariposa', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-elevacion-l', 'Pad Elevación L', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', 'Lash Lifting', false, 'Pad de elevación tipo L para lash lifting avanzado.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de elevación tipo L para lash lifting avanzado.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Elevación L', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-ld-simetricos', 'Pad LD Simétricos', 250, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', 'Lash Lifting', false, 'Pads LD simétricos para lash lifting profesional.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pads LD simétricos para lash lifting profesional.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad LD Simétricos', price = 250, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pad-nube', 'Pad Nube', 150, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', 'Lash Lifting', false, 'Pad de silicón diseño Nube para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pad de silicón diseño Nube para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', related_categories = '{"Lash Lifting"}', name = 'Pad Nube', price = 150, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-europea-tira', 'Pestaña Europea de Tira', 25, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p22-011-a2a1a932fdb14dab2f16494552819533-480-0.webp', 'Pestañas en Tira', false, 'Pestaña de tira estilo europeo.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestaña de tira estilo europeo.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p22-011-a2a1a932fdb14dab2f16494552819533-480-0.webp', related_categories = '{"Pestañas en Tira"}', name = 'Pestaña Europea de Tira', price = 25, category = 'Pestañas en Tira', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-decorada-tira', 'Pestaña Decorada de Tira', 20, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/p351-01-50b64373b52faf553616494555466379-480-0.webp', 'Pestañas en Tira', false, 'Pestaña de tira decorada para ocasiones especiales.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestaña de tira decorada para ocasiones especiales.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/p351-01-50b64373b52faf553616494555466379-480-0.webp', related_categories = '{"Pestañas en Tira"}', name = 'Pestaña Decorada de Tira', price = 20, category = 'Pestañas en Tira', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-d-colores', 'Pestaña (D) en Colores', 600, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/big-color-021-35719d95d60eae65d216847754951631-480-0.webp', 'Extensiones', false, 'Extensiones de pestañas curva D en colores variados.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Extensiones"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Extensiones de pestañas curva D en colores variados.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/big-color-021-35719d95d60eae65d216847754951631-480-0.webp', related_categories = '{"Extensiones"}', name = 'Pestaña (D) en Colores', price = 600, category = 'Extensiones', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('pestana-grupo-racimo-azul', 'Pestañas en Grupo o Racimo Azul', 22, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', 'Pestañas en Tira', false, 'Pestañas en grupo o racimo color azul.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Pestañas en Tira"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Pestañas en grupo o racimo color azul.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/sin-titulo-2-031964be3ce015c34417187368845684-480-0.webp', related_categories = '{"Pestañas en Tira"}', name = 'Pestañas en Grupo o Racimo Azul', price = 22, category = 'Pestañas en Tira', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('mini-cepillo-lash-lifting', 'Mini Cepillo para Lash Lifting', 40, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/fotoooo-19-263e9d2bf7a3e0676017188111757694-480-0.webp', 'Lash Lifting', false, 'Mini cepillo individual para lash lifting.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Mini cepillo individual para lash lifting.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/fotoooo-19-263e9d2bf7a3e0676017188111757694-480-0.webp', related_categories = '{"Lash Lifting","Accesorios"}', name = 'Mini Cepillo para Lash Lifting', price = 40, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (slug, name, price, compare_at_price, image_url, category, is_featured, description, benefits, includes, performance, specifications, gallery, video, related_categories, original_price, distributor_price, promotion)
VALUES ('50-cepillo-mini-laminado', '50 Cepillos Mini para Laminado', 160, NULL, 'https://acdn-us.mitiendanube.com/stores/694/809/products/minibrush-2-753349217864bef5fa17558789995527-480-0.webp', 'Lash Lifting', false, 'Paquete de 50 mini cepillos para laminado de cejas.', '{}', '{}', NULL, '{}', '{}', NULL, '{"Lash Lifting","Accesorios"}', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET description = 'Paquete de 50 mini cepillos para laminado de cejas.', image_url = 'https://acdn-us.mitiendanube.com/stores/694/809/products/minibrush-2-753349217864bef5fa17558789995527-480-0.webp', related_categories = '{"Lash Lifting","Accesorios"}', name = '50 Cepillos Mini para Laminado', price = 160, category = 'Lash Lifting', updated_at = CURRENT_TIMESTAMP;