DELETE FROM product_variants;
DELETE FROM variant_groups;
INSERT INTO variant_groups(name,attribute_names) VALUES('Extensiones Mink J.Denis','["Curva"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Extensiones Individuales Mixtas','["Curva","Grosor"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Extensiones Easy Fan J.Denis','["Curva","Grosor"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Abanicos Pre-hechos J.Denis','["Dimensión","Curva","Grosor","Largo"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Extensiones en Colores J.Denis','["Curva"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Rulos Desechables J.Denis','["Tamaño"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Rulos Adhesivos J.Denis','["Curva"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Tintura Tópica J.Denis','["Tono"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Pestañas en Grupo o Racimo','["Color"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Crema Lash Lifting J.Denis','["Paso"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Limpiador de Impurezas J.Denis','["Tipo de Piel"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Adhesivo Bálsamo J.Denis','["Presentación"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Pinzas Profesionales J.Denis','["Modelo"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Pads para Lash Lifting J.Denis','["Diseño"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Pestañas de Tira J.Denis','["Tipo"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Mini Cepillos J.Denis','["Uso"]'::jsonb);
INSERT INTO variant_groups(name,attribute_names) VALUES('Cepillos para Pestañas J.Denis','["Presentación"]'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Mink J.Denis' LIMIT 1),'pestana-mink-curva-c','{"Curva":"C"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Mink J.Denis' LIMIT 1),'pestana-mink-curva-d','{"Curva":"D"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-b-010-combo','{"Curva":"B","Grosor":"0.10"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-c-010-combo','{"Curva":"C","Grosor":"0.10"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-l-010-combo','{"Curva":"L","Grosor":"0.10"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-l-015-combo','{"Curva":"L","Grosor":"0.15"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-lc-010-combo','{"Curva":"LC","Grosor":"0.10"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-lc-015-combo','{"Curva":"LC","Grosor":"0.15"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Individuales Mixtas' LIMIT 1),'curva-cc-015-combo','{"Curva":"CC","Grosor":"0.15"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Easy Fan J.Denis' LIMIT 1),'easy-fan-curva-c','{"Curva":"C","Grosor":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Easy Fan J.Denis' LIMIT 1),'easy-fan-curva-d-005','{"Curva":"D","Grosor":"0.05"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones Easy Fan J.Denis' LIMIT 1),'easy-fan-curva-d-007','{"Curva":"D","Grosor":"0.07"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-3d-c-007','{"Dimensión":"3D","Curva":"C","Grosor":"0.07","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-2d-b-015-10','{"Dimensión":"2D","Curva":"B","Grosor":"0.15","Largo":"10mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-2d-b-015-12','{"Dimensión":"2D","Curva":"B","Grosor":"0.15","Largo":"12mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-2d-c-015-10','{"Dimensión":"2D","Curva":"C","Grosor":"0.15","Largo":"10mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-2d-j-015-10','{"Dimensión":"2D","Curva":"J","Grosor":"0.15","Largo":"10mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-2d-j-015-12','{"Dimensión":"2D","Curva":"J","Grosor":"0.15","Largo":"12mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-4d-b-015-10','{"Dimensión":"4D","Curva":"B","Grosor":"0.15","Largo":"10mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-4d-b-015-12','{"Dimensión":"4D","Curva":"B","Grosor":"0.15","Largo":"12mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-4d-c-005','{"Dimensión":"4D","Curva":"C","Grosor":"0.05","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-4d-c-007','{"Dimensión":"4D","Curva":"C","Grosor":"0.07","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-4d-d-005','{"Dimensión":"4D","Curva":"D","Grosor":"0.05","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-4d-d-007','{"Dimensión":"4D","Curva":"D","Grosor":"0.07","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-5d-b-015-10','{"Dimensión":"5D","Curva":"B","Grosor":"0.15","Largo":"10mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-5d-j-015-10','{"Dimensión":"5D","Curva":"J","Grosor":"0.15","Largo":"10mm"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-5d-c-005','{"Dimensión":"5D","Curva":"C","Grosor":"0.05","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-5d-c-007','{"Dimensión":"5D","Curva":"C","Grosor":"0.07","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-5d-d-005','{"Dimensión":"5D","Curva":"D","Grosor":"0.05","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Abanicos Pre-hechos J.Denis' LIMIT 1),'abanicos-5d-d-007','{"Dimensión":"5D","Curva":"D","Grosor":"0.07","Largo":"Mixta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones en Colores J.Denis' LIMIT 1),'pestana-c-colores','{"Curva":"C"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Extensiones en Colores J.Denis' LIMIT 1),'pestana-d-colores','{"Curva":"D"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Rulos Desechables J.Denis' LIMIT 1),'rulos-desechables-ch','{"Tamaño":"CH (Corta)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Rulos Desechables J.Denis' LIMIT 1),'rulos-desechables-m','{"Tamaño":"M (Media)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Rulos Desechables J.Denis' LIMIT 1),'rulos-desechables-g','{"Tamaño":"G (Amplia)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Rulos Adhesivos J.Denis' LIMIT 1),'rulos-adhesivos-curva-g','{"Curva":"G"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Rulos Adhesivos J.Denis' LIMIT 1),'rulos-adhesivos-curva-ch','{"Curva":"CH"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Rulos Adhesivos J.Denis' LIMIT 1),'rulos-adhesivos-curva-m','{"Curva":"M"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Tintura Tópica J.Denis' LIMIT 1),'tintura-topica-castano-medio','{"Tono":"Castaño Medio"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Tintura Tópica J.Denis' LIMIT 1),'tintura-topica-castano-oscuro','{"Tono":"Castaño Oscuro"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Tintura Tópica J.Denis' LIMIT 1),'tintura-topica-negro','{"Tono":"Negro"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pestañas en Grupo o Racimo' LIMIT 1),'pestana-grupo-racimo','{"Color":"Negro"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pestañas en Grupo o Racimo' LIMIT 1),'pestana-grupo-racimo-azul','{"Color":"Azul"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pestañas en Grupo o Racimo' LIMIT 1),'pestana-grupo-racimo-cafe','{"Color":"Café"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Crema Lash Lifting J.Denis' LIMIT 1),'crema-lifting-paso-1','{"Paso":"1 – Ondulante"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Crema Lash Lifting J.Denis' LIMIT 1),'crema-fijadora-paso-2','{"Paso":"2 – Fijadora"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Limpiador de Impurezas J.Denis' LIMIT 1),'limpiador-impurezas','{"Tipo de Piel":"Mixta / Grasa"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Limpiador de Impurezas J.Denis' LIMIT 1),'limpiador-impurezas-normal-seca','{"Tipo de Piel":"Normal / Seca"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Adhesivo Bálsamo J.Denis' LIMIT 1),'adhesivo-balsamo-20gr','{"Presentación":"20 gr"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Adhesivo Bálsamo J.Denis' LIMIT 1),'adhesivo-balsamo-30gr','{"Presentación":"Butter 30 gr"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-pestanas-tira','{"Modelo":"Pestañas de Tira"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-depilar','{"Modelo":"Depilar"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-punta-larga','{"Modelo":"Punta Larga"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-abanicos-sin-punta','{"Modelo":"Abanicos sin Punta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-punta-m12','{"Modelo":"Punta M-12"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-colocar-m18','{"Modelo":"Colocar M-18"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-ele-m19','{"Modelo":"Ele M-19"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-md14-punta','{"Modelo":"MD 14 en Punta"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pinzas Profesionales J.Denis' LIMIT 1),'pinza-md14-ele','{"Modelo":"MD 14 en Ele"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-rosas-micro-canales','{"Diseño":"Rosas con Micro Canales"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-nube','{"Diseño":"Nube"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-anime','{"Diseño":"Anime"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-curva-c','{"Diseño":"Curva C"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-rosa-sin-canales','{"Diseño":"Rosa sin Canales"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-superior-inferior','{"Diseño":"Superior e Inferior"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-colors-8p','{"Diseño":"Colors 8p"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-colors-6p','{"Diseño":"Colors 6p"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-oso','{"Diseño":"Oso"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-corrector-reversion','{"Diseño":"Corrector (Reversión)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-2-en-1','{"Diseño":"2 en 1"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-mariposa','{"Diseño":"Mariposa"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-elevacion-l','{"Diseño":"Elevación L"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pads para Lash Lifting J.Denis' LIMIT 1),'pad-ld-simetricos','{"Diseño":"LD Simétricos"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pestañas de Tira J.Denis' LIMIT 1),'pestana-americana-tira','{"Tipo":"Americana"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pestañas de Tira J.Denis' LIMIT 1),'pestana-europea-tira','{"Tipo":"Europea"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Pestañas de Tira J.Denis' LIMIT 1),'pestana-decorada-tira','{"Tipo":"Decorada"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Mini Cepillos J.Denis' LIMIT 1),'mini-cepillo-laminado','{"Uso":"Laminado (1 pza)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Mini Cepillos J.Denis' LIMIT 1),'mini-cepillo-lash-lifting','{"Uso":"Lash Lifting (1 pza)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Mini Cepillos J.Denis' LIMIT 1),'50-cepillo-mini-laminado','{"Uso":"Laminado (50 pzas)"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Cepillos para Pestañas J.Denis' LIMIT 1),'cepillos-pestanas-50','{"Presentación":"50 pzas Estándar"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Cepillos para Pestañas J.Denis' LIMIT 1),'cepillo-largo-100','{"Presentación":"100 pzas Largo"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Cepillos para Pestañas J.Denis' LIMIT 1),'cepillo-con-guarda','{"Presentación":"Con Guarda"}'::jsonb);
INSERT INTO product_variants(group_id,product_id,attributes) VALUES((SELECT id FROM variant_groups WHERE name='Cepillos para Pestañas J.Denis' LIMIT 1),'50-cepillos-pestanas','{"Presentación":"50 pzas Pro"}'::jsonb);
